export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'Grinning Face', keywords: ['happy', 'smile', 'joy', 'grin'] },
      { emoji: '😃', name: 'Grinning Face with Big Eyes', keywords: ['happy', 'joy', 'smile'] },
      { emoji: '😄', name: 'Grinning Face with Smiling Eyes', keywords: ['happy', 'joy', 'laugh'] },
      { emoji: '😁', name: 'Beaming Face with Smiling Eyes', keywords: ['happy', 'teeth', 'smile'] },
      { emoji: '😆', name: 'Grinning Squinting Face', keywords: ['happy', 'laugh', 'haha'] },
      { emoji: '😅', name: 'Grinning Face with Sweat', keywords: ['relief', 'hot', 'laugh', 'nervous'] },
      { emoji: '🤣', name: 'Rolling on the Floor Laughing', keywords: ['rofl', 'lol', 'laugh', 'funny'] },
      { emoji: '😂', name: 'Face with Tears of Joy', keywords: ['lol', 'laugh', 'tears', 'crying'] },
      { emoji: '🙂', name: 'Slightly Smiling Face', keywords: ['smile', 'happy'] },
      { emoji: '🙃', name: 'Upside-Down Face', keywords: ['silly', 'sarcasm', 'irony'] },
      { emoji: '😉', name: 'Winking Face', keywords: ['wink', 'flirt'] },
      { emoji: '😊', name: 'Smiling Face with Smiling Eyes', keywords: ['blush', 'warm', 'happy'] },
      { emoji: '😇', name: 'Smiling Face with Halo', keywords: ['angel', 'innocent', 'good'] },
      { emoji: '🥰', name: 'Smiling Face with Hearts', keywords: ['love', 'crush', 'adore', 'heart'] },
      { emoji: '😍', name: 'Smiling Face with Heart-Eyes', keywords: ['love', 'crush', 'heart'] },
      { emoji: '🤩', name: 'Star-Struck', keywords: ['star', 'eyes', 'wow', 'excited'] },
      { emoji: '😘', name: 'Face Blowing a Kiss', keywords: ['kiss', 'love', 'flirt'] },
      { emoji: '😋', name: 'Face Savoring Food', keywords: ['yum', 'delicious', 'tasty'] },
      { emoji: '😛', name: 'Face with Tongue', keywords: ['tongue', 'silly', 'joke'] },
      { emoji: '😜', name: 'Winking Face with Tongue', keywords: ['joke', 'playful', 'wink'] },
      { emoji: '🤪', name: 'Zany Face', keywords: ['crazy', 'wild', 'goofy'] },
      { emoji: '😝', name: 'Squinting Face with Tongue', keywords: ['prank', 'tongue', 'laugh'] },
      { emoji: '🤑', name: 'Money-Mouth Face', keywords: ['money', 'rich', 'cash', 'dollar'] },
      { emoji: '🤗', name: 'Smiling Face with Open Hands', keywords: ['hug', 'hands', 'warm'] },
      { emoji: '🤭', name: 'Face with Hand Over Mouth', keywords: ['oops', 'giggle', 'secret'] },
      { emoji: '🤫', name: 'Shushing Face', keywords: ['quiet', 'secret', 'shh'] },
      { emoji: '🤔', name: 'Thinking Face', keywords: ['think', 'hmmm', 'wonder'] },
      { emoji: '🤐', name: 'Zipper-Mouth Face', keywords: ['secret', 'silent', 'zip'] },
      { emoji: '🤨', name: 'Face with Raised Eyebrow', keywords: ['suspicious', 'doubt', 'skeptical'] },
      { emoji: '😐', name: 'Neutral Face', keywords: ['meh', 'poker', 'neutral'] },
      { emoji: '😑', name: 'Expressionless Face', keywords: ['blank', 'unimpressed'] },
      { emoji: '😶', name: 'Face Without Mouth', keywords: ['speechless', 'silent'] },
      { emoji: '😏', name: 'Smirking Face', keywords: ['smirk', 'cool', 'flirt'] },
      { emoji: '😒', name: 'Unamused Face', keywords: ['annoyed', 'grumpy', 'bored'] },
      { emoji: '🙄', name: 'Face with Rolling Eyes', keywords: ['eye roll', 'whatever'] },
      { emoji: '😬', name: 'Grimacing Face', keywords: ['awkward', 'cringe', 'eek'] },
      { emoji: '🤥', name: 'Lying Face', keywords: ['pinocchio', 'lie'] },
      { emoji: '😌', name: 'Relieved Face', keywords: ['relieved', 'calm', 'peace'] },
      { emoji: '😔', name: 'Pensive Face', keywords: ['sad', 'down', 'thoughtful'] },
      { emoji: '😪', name: 'Sleepy Face', keywords: ['tired', 'sleep', 'rest'] },
      { emoji: '🤤', name: 'Drooling Face', keywords: ['drool', 'craving'] },
      { emoji: '😴', name: 'Sleeping Face', keywords: ['zzz', 'sleep', 'tired'] },
      { emoji: '😷', name: 'Face with Medical Mask', keywords: ['sick', 'mask', 'covid'] },
      { emoji: '🤒', name: 'Face with Thermometer', keywords: ['sick', 'fever'] },
      { emoji: '🤕', name: 'Face with Head-Bandage', keywords: ['hurt', 'injured'] },
      { emoji: '🤢', name: 'Nauseated Face', keywords: ['gross', 'sick', 'disgust'] },
      { emoji: '🤮', name: 'Face Vomiting', keywords: ['sick', 'puke', 'vomit'] },
      { emoji: '🤧', name: 'Sneezing Face', keywords: ['sneeze', 'cold', 'sick'] },
      { emoji: '🥵', name: 'Hot Face', keywords: ['hot', 'heat', 'summer'] },
      { emoji: '🥶', name: 'Cold Face', keywords: ['cold', 'freeze', 'winter'] },
      { emoji: '🥴', name: 'Woozy Face', keywords: ['drunk', 'dizzy', 'tired'] },
      { emoji: '😵', name: 'Face with Crossed-Out Eyes', keywords: ['dizzy', 'dead', 'ko'] },
      { emoji: '🤯', name: 'Exploding Head', keywords: ['mind blown', 'shocked', 'wow'] },
      { emoji: '🤠', name: 'Cowboy Hat Face', keywords: ['cowboy', 'yeehaw'] },
      { emoji: '🥳', name: 'Partying Face', keywords: ['party', 'celebrate', 'birthday'] },
      { emoji: '😎', name: 'Smiling Face with Sunglasses', keywords: ['cool', 'sunglasses', 'awesome'] },
      { emoji: '🤓', name: 'Nerd Face', keywords: ['geek', 'nerd', 'smart'] },
      { emoji: '🧐', name: 'Face with Monocle', keywords: ['classy', 'inspect', 'fancy'] },
      { emoji: '😕', name: 'Confused Face', keywords: ['confused', 'huh'] },
      { emoji: '😟', name: 'Worried Face', keywords: ['worried', 'nervous'] },
      { emoji: '🙁', name: 'Slightly Frowning Face', keywords: ['sad', 'unhappy'] },
      { emoji: '😮', name: 'Face with Open Mouth', keywords: ['wow', 'surprise', 'omg'] },
      { emoji: '😯', name: 'Hushed Face', keywords: ['shocked', 'quiet'] },
      { emoji: '😲', name: 'Astonished Face', keywords: ['amazed', 'gasp'] },
      { emoji: '😳', name: 'Flushed Face', keywords: ['embarrassed', 'blush', 'shock'] },
      { emoji: '🥺', name: 'Pleading Face', keywords: ['puppy eyes', 'begging', 'please'] },
      { emoji: '😦', name: 'Frowning Face with Open Mouth', keywords: ['frown', 'aww'] },
      { emoji: '😨', name: 'Fearful Face', keywords: ['scared', 'fear', 'spook'] },
      { emoji: '😰', name: 'Anxious Face with Sweat', keywords: ['anxious', 'nervous', 'scared'] },
      { emoji: '😥', name: 'Sad but Relieved Face', keywords: ['phew', 'sweat', 'sad'] },
      { emoji: '😢', name: 'Crying Face', keywords: ['tear', 'sad', 'cry'] },
      { emoji: '😭', name: 'Loudly Crying Face', keywords: ['cry', 'tears', 'sob', 'sad'] },
      { emoji: '😱', name: 'Face Screaming in Fear', keywords: ['scream', 'scared', 'munch'] },
      { emoji: '😖', name: 'Confounded Face', keywords: ['frustrated', 'stressed'] },
      { emoji: '😣', name: 'Persevering Face', keywords: ['struggle', 'try'] },
      { emoji: '😞', name: 'Disappointed Face', keywords: ['sad', 'disappointed'] },
      { emoji: '😓', name: 'Downcast Face with Sweat', keywords: ['stress', 'hard work'] },
      { emoji: '😩', name: 'Weary Face', keywords: ['tired', 'frustrated'] },
      { emoji: '😫', name: 'Tired Face', keywords: ['exhausted', 'give up'] },
      { emoji: '🥱', name: 'Yawning Face', keywords: ['yawn', 'sleepy', 'bored'] },
      { emoji: '😤', name: 'Face with Steam From Nose', keywords: ['angry', 'triumph', 'proud'] },
      { emoji: '😡', name: 'Enraged Face', keywords: ['angry', 'mad', 'rage'] },
      { emoji: '😠', name: 'Angry Face', keywords: ['mad', 'annoyed'] },
      { emoji: '🤬', name: 'Face with Symbols on Mouth', keywords: ['curse', 'swear', 'angry'] },
      { emoji: '😈', name: 'Smiling Face with Horns', keywords: ['devil', 'evil', 'naughty'] },
      { emoji: '👿', name: 'Angry Face with Horns', keywords: ['devil', 'demon', 'angry'] },
      { emoji: '💀', name: 'Skull', keywords: ['dead', 'death', 'skeleton', 'danger'] },
      { emoji: '💩', name: 'Pile of Poo', keywords: ['poop', 'crap', 'funny'] },
      { emoji: '🤡', name: 'Clown Face', keywords: ['circus', 'joke', 'clown'] },
      { emoji: '👻', name: 'Ghost', keywords: ['halloween', 'spooky', 'boo'] },
      { emoji: '👽', name: 'Alien', keywords: ['ufo', 'space', 'extraterrestrial'] },
      { emoji: '🤖', name: 'Robot', keywords: ['bot', 'ai', 'machine'] },
    ],
  },
  {
    id: 'people',
    name: 'People & Gestures',
    icon: '👋',
    emojis: [
      { emoji: '👋', name: 'Waving Hand', keywords: ['hello', 'hi', 'bye', 'wave'] },
      { emoji: '🤚', name: 'Raised Back of Hand', keywords: ['hand', 'stop'] },
      { emoji: '🖐️', name: 'Hand with Fingers Splayed', keywords: ['five', 'hand'] },
      { emoji: '✋', name: 'Raised Hand', keywords: ['high five', 'stop', 'hand'] },
      { emoji: '🖖', name: 'Vulcan Salute', keywords: ['spock', 'star trek'] },
      { emoji: '👌', name: 'OK Hand', keywords: ['ok', 'perfect', 'agree'] },
      { emoji: '🤌', name: 'Pinched Fingers', keywords: ['italian', 'chef kiss', 'what'] },
      { emoji: '🤏', name: 'Pinching Hand', keywords: ['small', 'little', 'bit'] },
      { emoji: '✌️', name: 'Victory Hand', keywords: ['peace', 'two', 'v'] },
      { emoji: '🤞', name: 'Crossed Fingers', keywords: ['luck', 'hope', 'wish'] },
      { emoji: '🤟', name: 'Love-You Gesture', keywords: ['ily', 'love', 'rock'] },
      { emoji: '🤘', name: 'Sign of the Horns', keywords: ['rock on', 'metal'] },
      { emoji: '🤙', name: 'Call Me Hand', keywords: ['call', 'shaka', 'hang loose'] },
      { emoji: '👈', name: 'Backhand Index Pointing Left', keywords: ['left', 'point'] },
      { emoji: '👉', name: 'Backhand Index Pointing Right', keywords: ['right', 'point'] },
      { emoji: '👆', name: 'Backhand Index Pointing Up', keywords: ['up', 'point'] },
      { emoji: '👇', name: 'Backhand Index Pointing Down', keywords: ['down', 'point'] },
      { emoji: '☝️', name: 'Index Pointing Up', keywords: ['one', 'up', 'first'] },
      { emoji: '👍', name: 'Thumbs Up', keywords: ['yes', 'like', 'good', 'agree', 'approve'] },
      { emoji: '👎', name: 'Thumbs Down', keywords: ['no', 'dislike', 'bad', 'disapprove'] },
      { emoji: '✊', name: 'Raised Fist', keywords: ['power', 'fist'] },
      { emoji: '👊', name: 'Oncoming Fist', keywords: ['fist bump', 'punch'] },
      { emoji: '🤛', name: 'Left-Facing Fist', keywords: ['fist bump'] },
      { emoji: '🤜', name: 'Right-Facing Fist', keywords: ['fist bump'] },
      { emoji: '👏', name: 'Clapping Hands', keywords: ['applause', 'praise', 'bravo', 'clap'] },
      { emoji: '🙌', name: 'Raising Hands', keywords: ['celebrate', 'hooray', 'yay'] },
      { emoji: '👐', name: 'Open Hands', keywords: ['open', 'hug'] },
      { emoji: '🤲', name: 'Palms Up Together', keywords: ['prayer', 'cupped'] },
      { emoji: '🤝', name: 'Handshake', keywords: ['deal', 'agreement', 'partner', 'meet'] },
      { emoji: '🙏', name: 'Folded Hands', keywords: ['please', 'thank you', 'pray', 'namaste', 'hope'] },
      { emoji: '✍️', name: 'Writing Hand', keywords: ['write', 'letter', 'memo'] },
      { emoji: '💅', name: 'Nail Polish', keywords: ['beauty', 'slay', 'carefree'] },
      { emoji: '🤳', name: 'Selfie', keywords: ['phone', 'camera', 'photo'] },
      { emoji: '💪', name: 'Flexed Biceps', keywords: ['strong', 'muscle', 'power', 'gym', 'workout'] },
      { emoji: '🦾', name: 'Mechanical Arm', keywords: ['prosthetic', 'cyborg'] },
      { emoji: '🦿', name: 'Mechanical Leg', keywords: ['prosthetic', 'cyborg'] },
      { emoji: '🦵', name: 'Leg', keywords: ['kick', 'limb'] },
      { emoji: '🦶', name: 'Foot', keywords: ['kick', 'stomp'] },
      { emoji: '👂', name: 'Ear', keywords: ['listen', 'hear'] },
      { emoji: '🦻', name: 'Ear with Hearing Aid', keywords: ['accessible', 'hearing'] },
      { emoji: '👃', name: 'Nose', keywords: ['smell', 'sniff'] },
      { emoji: '🧠', name: 'Brain', keywords: ['smart', 'intellect', 'think'] },
      { emoji: '🫀', name: 'Anatomical Heart', keywords: ['heart', 'cardiology'] },
      { emoji: '🫁', name: 'Lungs', keywords: ['breath', 'air'] },
      { emoji: '👀', name: 'Eyes', keywords: ['look', 'see', 'watch', 'peek'] },
      { emoji: '👁️', name: 'Eye', keywords: ['vision', 'look'] },
      { emoji: '👅', name: 'Tongue', keywords: ['taste', 'lick'] },
      { emoji: '👄', name: 'Mouth', keywords: ['lips', 'kiss', 'talk'] },
      { emoji: '👶', name: 'Baby', keywords: ['child', 'infant'] },
      { emoji: '🧒', name: 'Child', keywords: ['kid', 'young'] },
      { emoji: '👦', name: 'Boy', keywords: ['male', 'young'] },
      { emoji: '👧', name: 'Girl', keywords: ['female', 'young'] },
      { emoji: '🧑', name: 'Person', keywords: ['adult', 'human'] },
      { emoji: '👱', name: 'Person: Blond Hair', keywords: ['blonde'] },
      { emoji: '👨', name: 'Man', keywords: ['male', 'guy'] },
      { emoji: '👩', name: 'Woman', keywords: ['female', 'lady'] },
      { emoji: '🧓', name: 'Older Person', keywords: ['elder', 'senior'] },
      { emoji: '👴', name: 'Old Man', keywords: ['grandfather', 'elder'] },
      { emoji: '👵', name: 'Old Woman', keywords: ['grandmother', 'elder'] },
      { emoji: '🙍', name: 'Person Frowning', keywords: ['disappointed', 'sad'] },
      { emoji: '🙎', name: 'Person Pouting', keywords: ['angry', 'upset'] },
      { emoji: '🙅', name: 'Person Gesturing No', keywords: ['stop', 'forbidden', 'no'] },
      { emoji: '🙆', name: 'Person Gesturing OK', keywords: ['ok', 'yes', 'agree'] },
      { emoji: '💁', name: 'Person Tipping Hand', keywords: ['help', 'sassy', 'info'] },
      { emoji: '🙋', name: 'Person Raising Hand', keywords: ['volunteer', 'question', 'here'] },
      { emoji: '🧏', name: 'Deaf Person', keywords: ['accessibility'] },
      { emoji: '🙇', name: 'Person Bowing', keywords: ['respect', 'apology', 'thanks'] },
      { emoji: '🤦', name: 'Person Facepalming', keywords: ['facepalm', 'disbelief', 'smh'] },
      { emoji: '🤷', name: 'Person Shrugging', keywords: ['shrug', 'idk', 'whatever', 'doubt'] },
      { emoji: '👨‍💼', name: 'Man Office Worker', keywords: ['business', 'worker', 'manager'] },
      { emoji: '👩‍💼', name: 'Woman Office Worker', keywords: ['business', 'worker', 'manager'] },
      { emoji: '👨‍💻', name: 'Man Technologist', keywords: ['developer', 'coder', 'programmer', 'software'] },
      { emoji: '👩‍💻', name: 'Woman Technologist', keywords: ['developer', 'coder', 'programmer', 'software'] },
    ],
  },
  {
    id: 'nature',
    name: 'Animals & Nature',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: 'Dog Face', keywords: ['puppy', 'pet', 'dog'] },
      { emoji: '🐱', name: 'Cat Face', keywords: ['kitten', 'pet', 'cat'] },
      { emoji: '🐭', name: 'Mouse Face', keywords: ['mouse', 'rodent'] },
      { emoji: '🐹', name: 'Hamster', keywords: ['pet', 'hamster'] },
      { emoji: '🐰', name: 'Rabbit Face', keywords: ['bunny', 'pet'] },
      { emoji: '🦊', name: 'Fox', keywords: ['nature', 'wild'] },
      { emoji: '🐻', name: 'Bear', keywords: ['nature', 'grizzly'] },
      { emoji: '🐼', name: 'Panda', keywords: ['nature', 'bamboo'] },
      { emoji: '🐨', name: 'Koala', keywords: ['nature', 'australia'] },
      { emoji: '🐯', name: 'Tiger Face', keywords: ['wild', 'tiger'] },
      { emoji: '🦁', name: 'Lion', keywords: ['king', 'jungle', 'wild'] },
      { emoji: '🐮', name: 'Cow Face', keywords: ['farm', 'milk'] },
      { emoji: '🐷', name: 'Pig Face', keywords: ['farm', 'pig'] },
      { emoji: '🐸', name: 'Frog', keywords: ['nature', 'green', 'ribbit'] },
      { emoji: '🐵', name: 'Monkey Face', keywords: ['jungle', 'banana'] },
      { emoji: '🐔', name: 'Chicken', keywords: ['farm', 'bird'] },
      { emoji: '🐧', name: 'Penguin', keywords: ['ice', 'bird', 'antarctica'] },
      { emoji: '🐦', name: 'Bird', keywords: ['nature', 'fly'] },
      { emoji: '🦅', name: 'Eagle', keywords: ['nature', 'fly', 'bird'] },
      { emoji: '🦆', name: 'Duck', keywords: ['bird', 'pond', 'quack'] },
      { emoji: '🦉', name: 'Owl', keywords: ['wise', 'night', 'bird'] },
      { emoji: '🦇', name: 'Bat', keywords: ['vampire', 'halloween'] },
      { emoji: '🐺', name: 'Wolf', keywords: ['wild', 'howl'] },
      { emoji: '🐗', name: 'Boar', keywords: ['wild', 'pig'] },
      { emoji: '🐴', name: 'Horse Face', keywords: ['farm', 'ride', 'equine'] },
      { emoji: '🦄', name: 'Unicorn', keywords: ['magic', 'fantasy', 'rare'] },
      { emoji: '🐝', name: 'Honeybee', keywords: ['bee', 'honey', 'insect'] },
      { emoji: '🐛', name: 'Bug', keywords: ['insect', 'caterpillar'] },
      { emoji: '🦋', name: 'Butterfly', keywords: ['nature', 'pretty', 'insect'] },
      { emoji: '🐌', name: 'Snail', keywords: ['slow', 'shell'] },
      { emoji: '🐞', name: 'Lady Beetle', keywords: ['ladybug', 'insect'] },
      { emoji: '🐜', name: 'Ant', keywords: ['insect', 'tiny'] },
      { emoji: '🕷️', name: 'Spider', keywords: ['halloween', 'web', 'arachnid'] },
      { emoji: '🐢', name: 'Turtle', keywords: ['slow', 'reptile', 'shell'] },
      { emoji: '🐍', name: 'Snake', keywords: ['reptile', 'danger'] },
      { emoji: '🦎', name: 'Lizard', keywords: ['reptile', 'nature'] },
      { emoji: '🦖', name: 'T-Rex', keywords: ['dinosaur', 'extinct'] },
      { emoji: '🦕', name: 'Sauropod', keywords: ['dinosaur', 'brontosaurus'] },
      { emoji: '🐙', name: 'Octopus', keywords: ['sea', 'ocean', 'tentacles'] },
      { emoji: '🦑', name: 'Squid', keywords: ['sea', 'ocean'] },
      { emoji: '🦐', name: 'Shrimp', keywords: ['seafood', 'crustacean'] },
      { emoji: '🦞', name: 'Lobster', keywords: ['seafood', 'crustacean'] },
      { emoji: '🦀', name: 'Crab', keywords: ['seafood', 'beach'] },
      { emoji: '🐡', name: 'Blowfish', keywords: ['fish', 'ocean'] },
      { emoji: '🐠', name: 'Tropical Fish', keywords: ['fish', 'aquarium'] },
      { emoji: '🐟', name: 'Fish', keywords: ['fish', 'sea'] },
      { emoji: '🐬', name: 'Dolphin', keywords: ['sea', 'intelligent'] },
      { emoji: '🐳', name: 'Spouting Whale', keywords: ['whale', 'ocean'] },
      { emoji: '🦈', name: 'Shark', keywords: ['danger', 'ocean', 'predator'] },
      { emoji: '🐊', name: 'Crocodile', keywords: ['reptile', 'alligator'] },
      { emoji: '🐆', name: 'Leopard', keywords: ['wild', 'cat'] },
      { emoji: '🦓', name: 'Zebra', keywords: ['stripes', 'safari'] },
      { emoji: '🦍', name: 'Gorilla', keywords: ['jungle', 'ape'] },
      { emoji: '🐘', name: 'Elephant', keywords: ['safari', 'trunk'] },
      { emoji: '🦛', name: 'Hippopotamus', keywords: ['hippo', 'safari'] },
      { emoji: '🦏', name: 'Rhinoceros', keywords: ['rhino', 'safari'] },
      { emoji: '🐪', name: 'Camel', keywords: ['desert', 'hump'] },
      { emoji: '🦒', name: 'Giraffe', keywords: ['safari', 'tall'] },
      { emoji: '🦘', name: 'Kangaroo', keywords: ['australia', 'hop'] },
      { emoji: '💐', name: 'Bouquet', keywords: ['flowers', 'gift'] },
      { emoji: '🌸', name: 'Cherry Blossom', keywords: ['flower', 'spring', 'sakura'] },
      { emoji: '💮', name: 'White Flower', keywords: ['flower', 'japanese'] },
      { emoji: '🏵️', name: 'Rosette', keywords: ['flower', 'decoration'] },
      { emoji: '🌹', name: 'Rose', keywords: ['flower', 'love', 'red'] },
      { emoji: '🌺', name: 'Hibiscus', keywords: ['flower', 'tropical'] },
      { emoji: '🌻', name: 'Sunflower', keywords: ['flower', 'sun', 'yellow'] },
      { emoji: '🌼', name: 'Blossom', keywords: ['flower', 'spring'] },
      { emoji: '🌷', name: 'Tulip', keywords: ['flower', 'spring'] },
      { emoji: '🌱', name: 'Seedling', keywords: ['plant', 'grow', 'nature'] },
      { emoji: '🌲', name: 'Evergreen Tree', keywords: ['tree', 'forest', 'nature'] },
      { emoji: '🌳', name: 'Deciduous Tree', keywords: ['tree', 'park', 'nature'] },
      { emoji: '🌴', name: 'Palm Tree', keywords: ['beach', 'summer', 'tropical'] },
      { emoji: '🌵', name: 'Cactus', keywords: ['desert', 'plant'] },
      { emoji: '🍀', name: 'Four Leaf Clover', keywords: ['lucky', 'irish', 'green'] },
      { emoji: '🍁', name: 'Maple Leaf', keywords: ['autumn', 'canada', 'fall'] },
      { emoji: '🍂', name: 'Fallen Leaf', keywords: ['autumn', 'nature'] },
      { emoji: '🍃', name: 'Leaf Fluttering in Wind', keywords: ['wind', 'leaf', 'nature'] },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: '🍕',
    emojis: [
      { emoji: '🍇', name: 'Grapes', keywords: ['fruit', 'wine'] },
      { emoji: '🍈', name: 'Melon', keywords: ['fruit'] },
      { emoji: '🍉', name: 'Watermelon', keywords: ['fruit', 'summer'] },
      { emoji: '🍊', name: 'Tangerine', keywords: ['orange', 'citrus'] },
      { emoji: '🍋', name: 'Lemon', keywords: ['sour', 'citrus'] },
      { emoji: '🍌', name: 'Banana', keywords: ['fruit', 'yellow'] },
      { emoji: '🍍', name: 'Pineapple', keywords: ['fruit', 'tropical'] },
      { emoji: '🥭', name: 'Mango', keywords: ['fruit', 'tropical'] },
      { emoji: '🍎', name: 'Red Apple', keywords: ['fruit', 'teacher'] },
      { emoji: '🍏', name: 'Green Apple', keywords: ['fruit'] },
      { emoji: '🍐', name: 'Pear', keywords: ['fruit'] },
      { emoji: '🍑', name: 'Peach', keywords: ['fruit', 'sweet'] },
      { emoji: '🍒', name: 'Cherries', keywords: ['fruit', 'red'] },
      { emoji: '🍓', name: 'Strawberry', keywords: ['fruit', 'berry'] },
      { emoji: '🫐', name: 'Blueberries', keywords: ['berry', 'fruit'] },
      { emoji: '🥝', name: 'Kiwi Fruit', keywords: ['fruit'] },
      { emoji: '🍅', name: 'Tomato', keywords: ['vegetable', 'red'] },
      { emoji: '🥥', name: 'Coconut', keywords: ['tropical', 'fruit'] },
      { emoji: '🥑', name: 'Avocado', keywords: ['guacamole', 'healthy'] },
      { emoji: '🍆', name: 'Eggplant', keywords: ['vegetable', 'aubergine'] },
      { emoji: '🥔', name: 'Potato', keywords: ['vegetable', 'fries'] },
      { emoji: '🥕', name: 'Carrot', keywords: ['vegetable', 'orange'] },
      { emoji: '🌽', name: 'Ear of Corn', keywords: ['vegetable', 'maize'] },
      { emoji: '🌶️', name: 'Hot Pepper', keywords: ['spicy', 'chili'] },
      { emoji: '🥒', name: 'Cucumber', keywords: ['vegetable', 'pickle'] },
      { emoji: '🥬', name: 'Leafy Green', keywords: ['salad', 'vegetable'] },
      { emoji: '🥦', name: 'Broccoli', keywords: ['vegetable', 'healthy'] },
      { emoji: '🧄', name: 'Garlic', keywords: ['cooking', 'flavor'] },
      { emoji: '🧅', name: 'Onion', keywords: ['cooking', 'flavor'] },
      { emoji: '🍄', name: 'Mushroom', keywords: ['fungus', 'nature'] },
      { emoji: '🥜', name: 'Peanuts', keywords: ['nuts', 'snack'] },
      { emoji: '🌰', name: 'Chestnut', keywords: ['nut'] },
      { emoji: '🍞', name: 'Bread', keywords: ['bakery', 'toast'] },
      { emoji: '🥐', name: 'Croissant', keywords: ['french', 'bakery', 'pastry'] },
      { emoji: '🥖', name: 'Baguette Bread', keywords: ['french', 'bread'] },
      { emoji: '🥨', name: 'Pretzel', keywords: ['snack', 'bavarian'] },
      { emoji: '🥯', name: 'Bagel', keywords: ['breakfast', 'bread'] },
      { emoji: '🥞', name: 'Pancakes', keywords: ['breakfast', 'syrup'] },
      { emoji: '🧇', name: 'Waffle', keywords: ['breakfast', 'syrup'] },
      { emoji: '🧀', name: 'Cheese Wedge', keywords: ['cheese', 'dairy'] },
      { emoji: '🍖', name: 'Meat on Bone', keywords: ['meat', 'bbq'] },
      { emoji: '🍗', name: 'Poultry Leg', keywords: ['chicken', 'drumstick'] },
      { emoji: '🥩', name: 'Cut of Meat', keywords: ['steak', 'beef'] },
      { emoji: '🥓', name: 'Bacon', keywords: ['breakfast', 'meat', 'pork'] },
      { emoji: '🍔', name: 'Hamburger', keywords: ['burger', 'fast food', 'beef'] },
      { emoji: '🍟', name: 'French Fries', keywords: ['fries', 'fast food', 'potato'] },
      { emoji: '🍕', name: 'Pizza', keywords: ['cheese', 'slice', 'italian', 'fast food'] },
      { emoji: '🌭', name: 'Hot Dog', keywords: ['sausage', 'fast food'] },
      { emoji: '🥪', name: 'Sandwich', keywords: ['lunch', 'bread'] },
      { emoji: '🌮', name: 'Taco', keywords: ['mexican', 'snack'] },
      { emoji: '🌯', name: 'Burrito', keywords: ['mexican', 'wrap'] },
      { emoji: '🥙', name: 'Stuffed Flatbread', keywords: ['pita', 'gyro', 'kebab'] },
      { emoji: '🧆', name: 'Falafel', keywords: ['middle eastern', 'vegetarian'] },
      { emoji: '🥚', name: 'Egg', keywords: ['breakfast', 'chicken'] },
      { emoji: '🍳', name: 'Cooking', keywords: ['fried egg', 'pan'] },
      { emoji: '🥘', name: 'Shallow Pan of Food', keywords: ['paella', 'stew'] },
      { emoji: '🍲', name: 'Pot of Food', keywords: ['soup', 'stew'] },
      { emoji: '🥣', name: 'Bowl with Spoon', keywords: ['cereal', 'soup'] },
      { emoji: '🥗', name: 'Green Salad', keywords: ['healthy', 'vegetables'] },
      { emoji: '🍿', name: 'Popcorn', keywords: ['movie', 'snack'] },
      { emoji: '🧈', name: 'Butter', keywords: ['dairy', 'cooking'] },
      { emoji: '🧂', name: 'Salt', keywords: ['seasoning', 'flavor'] },
      { emoji: '🥫', name: 'Canned Food', keywords: ['preserve', 'can'] },
      { emoji: '🍱', name: 'Bento Box', keywords: ['japanese', 'lunch'] },
      { emoji: '🍘', name: 'Rice Cracker', keywords: ['japanese', 'snack'] },
      { emoji: '🍙', name: 'Rice Ball', keywords: ['onigiri', 'japanese'] },
      { emoji: '🍚', name: 'Cooked Rice', keywords: ['asian', 'bowl'] },
      { emoji: '🍛', name: 'Curry Rice', keywords: ['indian', 'japanese', 'spicy'] },
      { emoji: '🍜', name: 'Steaming Bowl', keywords: ['ramen', 'noodles', 'soup'] },
      { emoji: '🍝', name: 'Spaghetti', keywords: ['pasta', 'italian'] },
      { emoji: '🍠', name: 'Roasted Sweet Potato', keywords: ['yam', 'snack'] },
      { emoji: '🍢', name: 'Oden', keywords: ['japanese', 'skewer'] },
      { emoji: '🍣', name: 'Sushi', keywords: ['japanese', 'fish', 'rice'] },
      { emoji: '🍦', name: 'Soft Ice Cream', keywords: ['dessert', 'summer', 'cone'] },
      { emoji: '🍧', name: 'Shaved Ice', keywords: ['dessert', 'summer'] },
      { emoji: '🍨', name: 'Ice Cream', keywords: ['dessert', 'bowl'] },
      { emoji: '🍩', name: 'Doughnut', keywords: ['donut', 'sweet', 'bakery'] },
      { emoji: '🍪', name: 'Cookie', keywords: ['chocolate chip', 'biscuit', 'sweet'] },
      { emoji: '🎂', name: 'Birthday Cake', keywords: ['cake', 'celebration', 'party'] },
      { emoji: '🍰', name: 'Shortcake', keywords: ['cake', 'slice', 'strawberry'] },
      { emoji: '🧁', name: 'Cupcake', keywords: ['bakery', 'sweet'] },
      { emoji: '🥧', name: 'Pie', keywords: ['bakery', 'dessert'] },
      { emoji: '🍫', name: 'Chocolate Bar', keywords: ['sweet', 'candy'] },
      { emoji: '🍬', name: 'Candy', keywords: ['sweet', 'sugar'] },
      { emoji: '🍭', name: 'Lollipop', keywords: ['sweet', 'candy'] },
      { emoji: '🍮', name: 'Custard', keywords: ['dessert', 'pudding'] },
      { emoji: '🍯', name: 'Honey Pot', keywords: ['sweet', 'honey'] },
      { emoji: '☕', name: 'Hot Beverage', keywords: ['coffee', 'tea', 'cafe', 'morning'] },
      { emoji: '🫖', name: 'Teapot', keywords: ['tea', 'pot'] },
      { emoji: '🍵', name: 'Teacup Without Handle', keywords: ['green tea', 'matcha'] },
      { emoji: '🍶', name: 'Sake', keywords: ['japanese', 'alcohol'] },
      { emoji: '🍾', name: 'Bottle with Popping Cork', keywords: ['champagne', 'celebrate'] },
      { emoji: '🍷', name: 'Wine Glass', keywords: ['wine', 'alcohol', 'drink'] },
      { emoji: '🍸', name: 'Cocktail Glass', keywords: ['martini', 'drink', 'party'] },
      { emoji: '🍹', name: 'Tropical Drink', keywords: ['vacation', 'cocktail'] },
      { emoji: '🍺', name: 'Beer Mug', keywords: ['beer', 'cheers', 'drink', 'pub'] },
      { emoji: '🍻', name: 'Clinking Beer Mugs', keywords: ['cheers', 'beer', 'celebrate'] },
      { emoji: '🥂', name: 'Clinking Glasses', keywords: ['cheers', 'toast', 'celebrate'] },
      { emoji: '🥃', name: 'Tumbler Glass', keywords: ['whiskey', 'liquor'] },
      { emoji: '🥤', name: 'Cup with Straw', keywords: ['soda', 'drink', 'juice'] },
      { emoji: '🧋', name: 'Bubble Tea', keywords: ['boba', 'tea', 'drink'] },
      { emoji: '🧃', name: 'Beverage Box', keywords: ['juice box', 'drink'] },
      { emoji: '🧉', name: 'Mate', keywords: ['drink', 'caffeine'] },
      { emoji: '🧊', name: 'Ice', keywords: ['cold', 'cube'] },
    ],
  },
  {
    id: 'activities',
    name: 'Activities & Objects',
    icon: '🎉',
    emojis: [
      { emoji: '🎉', name: 'Party Popper', keywords: ['celebrate', 'congrats', 'party', 'tada', 'yay'] },
      { emoji: '🎊', name: 'Confetti Ball', keywords: ['celebration', 'party'] },
      { emoji: '🎁', name: 'Wrapped Gift', keywords: ['present', 'birthday', 'box', 'gift'] },
      { emoji: '🎈', name: 'Balloon', keywords: ['party', 'birthday'] },
      { emoji: '🏆', name: 'Trophy', keywords: ['winner', 'champion', 'first', 'prize'] },
      { emoji: '🥇', name: '1st Place Medal', keywords: ['first', 'gold', 'winner'] },
      { emoji: '🥈', name: '2nd Place Medal', keywords: ['second', 'silver'] },
      { emoji: '🥉', name: '3rd Place Medal', keywords: ['third', 'bronze'] },
      { emoji: '⚽', name: 'Soccer Ball', keywords: ['football', 'sport'] },
      { emoji: '🏀', name: 'Basketball', keywords: ['sport', 'nba'] },
      { emoji: '🏈', name: 'American Football', keywords: ['sport', 'nfl'] },
      { emoji: '⚾', name: 'Baseball', keywords: ['sport', 'mlb'] },
      { emoji: '🥎', name: 'Softball', keywords: ['sport'] },
      { emoji: '🎾', name: 'Tennis', keywords: ['sport', 'ball'] },
      { emoji: '🏐', name: 'Volleyball', keywords: ['sport'] },
      { emoji: '🏉', name: 'Rugby Football', keywords: ['sport'] },
      { emoji: '🥏', name: 'Flying Disc', keywords: ['frisbee'] },
      { emoji: '🎱', name: 'Pool 8 Ball', keywords: ['billiards', 'game'] },
      { emoji: '🏓', name: 'Ping Pong', keywords: ['table tennis', 'sport'] },
      { emoji: '🏸', name: 'Badminton', keywords: ['sport'] },
      { emoji: '🥊', name: 'Boxing Glove', keywords: ['fight', 'sport'] },
      { emoji: '🥋', name: 'Martial Arts Uniform', keywords: ['karate', 'judo'] },
      { emoji: '🎯', name: 'Bullseye', keywords: ['target', 'hit', 'direct'] },
      { emoji: '⛳', name: 'Flag in Hole', keywords: ['golf'] },
      { emoji: '🎮', name: 'Video Game', keywords: ['gaming', 'play', 'controller'] },
      { emoji: '🕹️', name: 'Joystick', keywords: ['arcade', 'game'] },
      { emoji: '🎲', name: 'Game Die', keywords: ['dice', 'luck', 'chance'] },
      { emoji: '♟️', name: 'Chess Pawn', keywords: ['chess', 'game', 'strategy'] },
      { emoji: '🧩', name: 'Puzzle Piece', keywords: ['clue', 'game'] },
      { emoji: '📱', name: 'Mobile Phone', keywords: ['smartphone', 'cell', 'iphone', 'android'] },
      { emoji: '📲', name: 'Mobile Phone with Arrow', keywords: ['call', 'message'] },
      { emoji: '💻', name: 'Laptop', keywords: ['computer', 'pc', 'macbook', 'work'] },
      { emoji: '🖥️', name: 'Desktop Computer', keywords: ['pc', 'screen'] },
      { emoji: '🖨️', name: 'Printer', keywords: ['paper', 'office'] },
      { emoji: '⌨️', name: 'Keyboard', keywords: ['type', 'computer'] },
      { emoji: '🖱️', name: 'Computer Mouse', keywords: ['click'] },
      { emoji: '💾', name: 'Floppy Disk', keywords: ['save', 'disk'] },
      { emoji: '💿', name: 'Optical Disk', keywords: ['cd', 'dvd'] },
      { emoji: '📷', name: 'Camera', keywords: ['photo', 'picture'] },
      { emoji: '📸', name: 'Camera with Flash', keywords: ['photo'] },
      { emoji: '📹', name: 'Video Camera', keywords: ['movie', 'film'] },
      { emoji: '🎥', name: 'Movie Camera', keywords: ['cinema', 'film'] },
      { emoji: '📽️', name: 'Film Projector', keywords: ['cinema', 'movie'] },
      { emoji: '📞', name: 'Telephone Receiver', keywords: ['call', 'phone'] },
      { emoji: '☎️', name: 'Telephone', keywords: ['call', 'phone'] },
      { emoji: '📟', name: 'Pager', keywords: ['device', 'retro'] },
      { emoji: '📠', name: 'Fax Machine', keywords: ['office'] },
      { emoji: '📺', name: 'Television', keywords: ['tv', 'show'] },
      { emoji: '📻', name: 'Radio', keywords: ['music', 'broadcast'] },
      { emoji: '🎙️', name: 'Studio Microphone', keywords: ['podcast', 'sing', 'record'] },
      { emoji: '🎚️', name: 'Level Slider', keywords: ['volume', 'audio'] },
      { emoji: '🎛️', name: 'Control Knobs', keywords: ['audio', 'music'] },
      { emoji: '⏱️', name: 'Stopwatch', keywords: ['time', 'timer'] },
      { emoji: '⏲️', name: 'Timer Clock', keywords: ['time', 'cook'] },
      { emoji: '⏰', name: 'Alarm Clock', keywords: ['wake up', 'morning', 'time'] },
      { emoji: '🕰️', name: 'Mantelpiece Clock', keywords: ['time'] },
      { emoji: '⏳', name: 'Hourglass Not Done', keywords: ['time', 'wait', 'loading'] },
      { emoji: '⌛', name: 'Hourglass Done', keywords: ['time', 'finished'] },
      { emoji: '💡', name: 'Light Bulb', keywords: ['idea', 'bright', 'smart', 'tip'] },
      { emoji: '🔦', name: 'Flashlight', keywords: ['light', 'torch'] },
      { emoji: '🕯️', name: 'Candle', keywords: ['light', 'flame'] },
      { emoji: '🧯', name: 'Fire Extinguisher', keywords: ['safety', 'fire'] },
      { emoji: '💸', name: 'Money with Wings', keywords: ['dollar', 'cash', 'spending', 'flying'] },
      { emoji: '💵', name: 'Dollar Banknote', keywords: ['money', 'cash', 'usd'] },
      { emoji: '💴', name: 'Yen Banknote', keywords: ['money', 'japan'] },
      { emoji: '💶', name: 'Euro Banknote', keywords: ['money', 'europe'] },
      { emoji: '💷', name: 'Pound Banknote', keywords: ['money', 'uk'] },
      { emoji: '💰', name: 'Money Bag', keywords: ['wealth', 'rich', 'dollar', 'cash'] },
      { emoji: '💳', name: 'Credit Card', keywords: ['payment', 'buy', 'bank'] },
      { emoji: '💎', name: 'Gem Stone', keywords: ['diamond', 'valuable', 'rich'] },
      { emoji: '⚖️', name: 'Balance Scale', keywords: ['justice', 'law', 'balance'] },
      { emoji: '🧰', name: 'Toolbox', keywords: ['tools', 'fix'] },
      { emoji: '🔧', name: 'Wrench', keywords: ['tool', 'fix', 'settings'] },
      { emoji: '🔨', name: 'Hammer', keywords: ['tool', 'build'] },
      { emoji: '⚒️', name: 'Hammer and Pick', keywords: ['tools', 'mining'] },
      { emoji: '🛠️', name: 'Hammer and Wrench', keywords: ['tools', 'settings', 'fix'] },
      { emoji: '🗡️', name: 'Dagger', keywords: ['sword', 'weapon'] },
      { emoji: '⚔️', name: 'Crossed Swords', keywords: ['battle', 'fight'] },
      { emoji: '🛡️', name: 'Shield', keywords: ['protection', 'defense', 'security'] },
      { emoji: '🔑', name: 'Key', keywords: ['password', 'lock', 'access', 'secret'] },
      { emoji: '🗝️', name: 'Old Key', keywords: ['lock', 'secret'] },
      { emoji: '🔒', name: 'Locked', keywords: ['secure', 'privacy', 'closed'] },
      { emoji: '🔓', name: 'Unlocked', keywords: ['open', 'insecure'] },
      { emoji: '📦', name: 'Package', keywords: ['delivery', 'box', 'shipping', 'order', 'parcel'] },
      { emoji: '📫', name: 'Closed Mailbox with Raised Flag', keywords: ['mail', 'letter'] },
      { emoji: '📬', name: 'Open Mailbox with Raised Flag', keywords: ['mail', 'inbox'] },
      { emoji: '✉️', name: 'Envelope', keywords: ['email', 'mail', 'message', 'letter'] },
      { emoji: '📧', name: 'E-Mail', keywords: ['email', 'communication'] },
      { emoji: '📨', name: 'Incoming Envelope', keywords: ['received', 'mail'] },
      { emoji: '📩', name: 'Envelope with Arrow', keywords: ['sent', 'mail'] },
      { emoji: '📝', name: 'Memo', keywords: ['note', 'document', 'write'] },
      { emoji: '📁', name: 'File Folder', keywords: ['directory', 'files'] },
      { emoji: '📂', name: 'Open File Folder', keywords: ['folder', 'documents'] },
      { emoji: '📄', name: 'Page Facing Up', keywords: ['document', 'file', 'paper'] },
      { emoji: '📜', name: 'Scroll', keywords: ['paper', 'document'] },
      { emoji: '📊', name: 'Bar Chart', keywords: ['analytics', 'growth', 'stats', 'graph'] },
      { emoji: '📈', name: 'Chart Increasing', keywords: ['up', 'growth', 'success', 'profit'] },
      { emoji: '📉', name: 'Chart Decreasing', keywords: ['down', 'loss', 'stats'] },
      { emoji: '📌', name: 'Pushpin', keywords: ['pin', 'location', 'note'] },
      { emoji: '📍', name: 'Round Pushpin', keywords: ['location', 'map', 'pin'] },
      { emoji: '📎', name: 'Paperclip', keywords: ['attachment', 'attach'] },
      { emoji: '🔍', name: 'Magnifying Glass Tilted Left', keywords: ['search', 'find', 'zoom'] },
      { emoji: '🔎', name: 'Magnifying Glass Tilted Right', keywords: ['search', 'find'] },
    ],
  },
  {
    id: 'symbols',
    name: 'Symbols & Flags',
    icon: '✨',
    emojis: [
      { emoji: '❤️', name: 'Red Heart', keywords: ['love', 'heart', 'like'] },
      { emoji: '🧡', name: 'Orange Heart', keywords: ['love', 'orange'] },
      { emoji: '💛', name: 'Yellow Heart', keywords: ['friendship', 'yellow'] },
      { emoji: '💚', name: 'Green Heart', keywords: ['nature', 'green'] },
      { emoji: '💙', name: 'Blue Heart', keywords: ['trust', 'blue'] },
      { emoji: '💜', name: 'Purple Heart', keywords: ['purple'] },
      { emoji: '🖤', name: 'Black Heart', keywords: ['black', 'dark'] },
      { emoji: '🤍', name: 'White Heart', keywords: ['pure', 'white'] },
      { emoji: '🤎', name: 'Brown Heart', keywords: ['brown'] },
      { emoji: '💔', name: 'Broken Heart', keywords: ['heartbreak', 'sad'] },
      { emoji: '❣️', name: 'Heart Exclamation', keywords: ['punctuation', 'love'] },
      { emoji: '💕', name: 'Two Hearts', keywords: ['love', 'crush'] },
      { emoji: '💞', name: 'Revolving Hearts', keywords: ['love'] },
      { emoji: '💓', name: 'Beating Heart', keywords: ['heartbeat', 'love'] },
      { emoji: '💗', name: 'Growing Heart', keywords: ['love', 'affection'] },
      { emoji: '💖', name: 'Sparkling Heart', keywords: ['sparkle', 'love', 'shine'] },
      { emoji: '💘', name: 'Heart with Arrow', keywords: ['cupid', 'love'] },
      { emoji: '💝', name: 'Heart with Ribbon', keywords: ['gift', 'love'] },
      { emoji: '✨', name: 'Sparkles', keywords: ['magic', 'shine', 'clean', 'ai', 'special'] },
      { emoji: '⭐', name: 'Star', keywords: ['favorite', 'gold', 'rating'] },
      { emoji: '🌟', name: 'Glowing Star', keywords: ['shine', 'bright'] },
      { emoji: '💫', name: 'Dizzy', keywords: ['star', 'sparkle'] },
      { emoji: '🔥', name: 'Fire', keywords: ['hot', 'lit', 'flame', 'trending', 'awesome'] },
      { emoji: '💥', name: 'Collision', keywords: ['boom', 'explode', 'bang'] },
      { emoji: '⚡', name: 'High Voltage', keywords: ['lightning', 'fast', 'zap', 'energy', 'power'] },
      { emoji: '🚀', name: 'Rocket', keywords: ['launch', 'fast', 'moon', 'ship'] },
      { emoji: '💯', name: 'Hundred Points', keywords: ['100', 'perfect', 'score', 'keep it real'] },
      { emoji: '✅', name: 'Check Mark Button', keywords: ['done', 'yes', 'verified', 'complete', 'ok'] },
      { emoji: '✔️', name: 'Check Mark', keywords: ['check', 'done'] },
      { emoji: '❌', name: 'Cross Mark', keywords: ['no', 'wrong', 'cancel', 'delete', 'error'] },
      { emoji: '❎', name: 'Cross Mark Button', keywords: ['cancel', 'no'] },
      { emoji: '➕', name: 'Plus', keywords: ['add', 'more', 'math'] },
      { emoji: '➖', name: 'Minus', keywords: ['subtract', 'less', 'math'] },
      { emoji: '➗', name: 'Division', keywords: ['divide', 'math'] },
      { emoji: '✖️', name: 'Multiply', keywords: ['times', 'math'] },
      { emoji: '❓', name: 'Question Mark', keywords: ['help', 'what', 'confused'] },
      { emoji: '❗', name: 'Exclamation Mark', keywords: ['important', 'alert', 'warning'] },
      { emoji: '⚠️', name: 'Warning', keywords: ['caution', 'alert', 'danger'] },
      { emoji: '⛔', name: 'No Entry', keywords: ['stop', 'forbidden'] },
      { emoji: '🚫', name: 'Prohibited', keywords: ['forbidden', 'no'] },
      { emoji: '🟢', name: 'Green Circle', keywords: ['online', 'active', 'green'] },
      { emoji: '🔴', name: 'Red Circle', keywords: ['offline', 'stop', 'red'] },
      { emoji: '🟡', name: 'Yellow Circle', keywords: ['away', 'pending', 'yellow'] },
      { emoji: '🔵', name: 'Blue Circle', keywords: ['blue'] },
      { emoji: '🟣', name: 'Purple Circle', keywords: ['purple'] },
      { emoji: '⚪', name: 'White Circle', keywords: ['white'] },
      { emoji: '⚫', name: 'Black Circle', keywords: ['black'] },
      { emoji: '🟠', name: 'Orange Circle', keywords: ['orange'] },
      { emoji: '🟤', name: 'Brown Circle', keywords: ['brown'] },
      { emoji: '🟦', name: 'Blue Square', keywords: ['blue', 'block'] },
      { emoji: '🟩', name: 'Green Square', keywords: ['green', 'block'] },
      { emoji: '🟨', name: 'Yellow Square', keywords: ['yellow', 'block'] },
      { emoji: '🟥', name: 'Red Square', keywords: ['red', 'block'] },
      { emoji: '🏁', name: 'Chequered Flag', keywords: ['finish', 'race', 'done'] },
      { emoji: '🚩', name: 'Triangular Flag', keywords: ['red flag', 'warning', 'location'] },
      { emoji: '🏳️', name: 'White Flag', keywords: ['surrender', 'peace'] },
      { emoji: '🏴', name: 'Black Flag', keywords: ['pirate', 'flag'] },
    ],
  },
];

/**
 * Filter emojis across all categories by a search query string.
 */
export function searchEmojis(query: string): EmojiItem[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];

  const results: EmojiItem[] = [];
  const seen = new Set<string>();

  for (const cat of EMOJI_CATEGORIES) {
    for (const item of cat.emojis) {
      if (seen.has(item.emoji)) continue;

      const nameMatch = item.name.toLowerCase().includes(normalized);
      const keywordMatch = item.keywords.some((k) => k.toLowerCase().includes(normalized));

      if (nameMatch || keywordMatch) {
        results.push(item);
        seen.add(item.emoji);
      }
    }
  }

  return results;
}
