// ============================================================
// POST /api/account/members/create
//
// Direct IDP (Identity Provider) account creation endpoint. Allows the
// owner to create a new Supabase Auth user with email/password
// and immediately assign them to the caller's workspace as a member
// with granular section permissions.
// ============================================================

import { NextResponse } from "next/server";

import { requireRole, toErrorResponse } from "@/lib/auth/account";
import { supabaseAdmin } from "@/lib/auth/admin-client";
import {
  checkRateLimit,
  rateLimitResponse,
  RATE_LIMITS,
} from "@/lib/rate-limit";
import type { AccountMember, AccountRole, MemberPermissions } from "@/types";

export async function POST(request: Request) {
  try {
    const ctx = await requireRole("owner");

    const limit = checkRateLimit(
      `admin:memberCreate:${ctx.userId}`,
      RATE_LIMITS.adminAction,
    );
    if (!limit.success) return rateLimitResponse(limit);

    const body = (await request.json().catch(() => null)) as {
      fullName?: string;
      email?: string;
      password?: string;
      permissions?: unknown;
    } | null;

    const { fullName, email, password, permissions } = body ?? {};

    if (!fullName || typeof fullName !== "string" || !fullName.trim()) {
      return NextResponse.json(
        { error: "Full name is required" },
        { status: 400 },
      );
    }
    if (!email || typeof email !== "string" || !email.includes("@")) {
      return NextResponse.json(
        { error: "Valid email is required" },
        { status: 400 },
      );
    }
    if (!password || typeof password !== "string" || password.length < 6) {
      return NextResponse.json(
        { error: "Password must be at least 6 characters" },
        { status: 400 },
      );
    }


    let validPermissions: MemberPermissions | null = null;
    if (permissions && typeof permissions === "object") {
      const p = permissions as Record<string, unknown>;
      validPermissions = {
        inbox: Boolean(p.inbox ?? true),
        dashboard: Boolean(p.dashboard ?? false),
        contacts: Boolean(p.contacts ?? false),
        pipelines: Boolean(p.pipelines ?? false),
        broadcasts: Boolean(p.broadcasts ?? false),
        automations: Boolean(p.automations ?? false),
        settings: Boolean(p.settings ?? false),
        settings_whatsapp: Boolean(p.settings_whatsapp ?? true),
        settings_templates: Boolean(p.settings_templates ?? true),
        settings_quick_replies: Boolean(p.settings_quick_replies ?? true),
        settings_fields: Boolean(p.settings_fields ?? true),
        settings_deals: Boolean(p.settings_deals ?? true),
        settings_members: Boolean(p.settings_members ?? false),
        settings_api: Boolean(p.settings_api ?? false),
      };
    }

    const adminClient = supabaseAdmin();

    // 1. Create Supabase Auth user with confirmed email
    const { data: newUser, error: createError } = await adminClient.auth.admin.createUser({
      email: email.trim(),
      password: password,
      email_confirm: true,
      user_metadata: {
        full_name: fullName.trim(),
      },
    });

    if (createError) {
      console.error("[POST /api/account/members/create] createUser error:", createError);
      return NextResponse.json(
        { error: createError.message || "Failed to create user account" },
        { status: 400 },
      );
    }
    if (!newUser.user) {
      return NextResponse.json(
        { error: "Failed to create user account" },
        { status: 500 },
      );
    }

    // 2. Assign to caller's workspace, setting role & permissions.
    // Notice that service_role bypasses the enforce_profile_privilege_columns
    // trigger in migration 034.
    const { data: updatedProfile, error: profileError } = await adminClient
      .from("profiles")
      .update({
        account_id: ctx.accountId,
        account_role: 'member' as const,
        permissions: validPermissions,
        full_name: fullName.trim(),
      })
      .eq("user_id", newUser.user.id)
      .select("user_id, full_name, email, avatar_url, account_role, permissions, created_at")
      .single();

    if (profileError || !updatedProfile) {
      console.error("[POST /api/account/members/create] update profile error:", profileError);
      // Clean up the created auth user if workspace assignment fails
      await adminClient.auth.admin.deleteUser(newUser.user.id).catch(() => {});
      return NextResponse.json(
        { error: "Failed to assign workspace membership" },
        { status: 500 },
      );
    }

    // 3. Clean up the temporary orphan personal account generated by signup trigger
    try {
      await adminClient
        .from("accounts")
        .delete()
        .eq("owner_user_id", newUser.user.id);
    } catch (err) {
      console.error("[POST /api/account/members/create] orphan account cleanup error:", err);
    }

    const member: AccountMember = {
      user_id: updatedProfile.user_id,
      full_name: updatedProfile.full_name ?? fullName.trim(),
      email: updatedProfile.email ?? email.trim(),
      avatar_url: updatedProfile.avatar_url,
      role: updatedProfile.account_role as AccountRole,
      permissions: updatedProfile.permissions ?? validPermissions,
      is_active: true,
      joined_at: updatedProfile.created_at,
    };

    return NextResponse.json({ member }, { status: 201 });
  } catch (err) {
    return toErrorResponse(err);
  }
}
