-- ============================================================
-- 042_seed_landing_content.sql
-- Seed default landing page content
-- ============================================================

-- Site settings (singleton)
INSERT INTO site_settings (site_name, tagline) 
VALUES ('Replai', 'AI-Powered WhatsApp CRM')
ON CONFLICT DO NOTHING;

-- Landing sections
INSERT INTO landing_sections (section_key, title, subtitle, body_text, cta_primary_text, cta_primary_link, cta_secondary_text, cta_secondary_link, position) VALUES
('hero', 'Your AI-Powered WhatsApp CRM', 'Shared inbox, smart automations, broadcast campaigns, and AI replies — all in one platform. Built for teams that sell on WhatsApp.', NULL, 'Start Free Trial', '/signup', 'Watch Demo', '#demo', 1),
('social_proof', 'Trusted by 500+ businesses worldwide', NULL, NULL, NULL, NULL, NULL, NULL, 2),
('features', 'Everything you need to sell on WhatsApp', 'Replai brings together the tools your team needs to manage customer conversations at scale.', NULL, NULL, NULL, NULL, NULL, 3),
('how_it_works', 'Get started in 3 simple steps', 'From setup to your first AI-powered reply in under 10 minutes.', NULL, NULL, NULL, NULL, NULL, 4),
('ai_highlight', 'AI That Actually Understands Your Business', 'Upload your docs, FAQs, and product info. Replai builds a knowledge base and uses hybrid retrieval (full-text + vector search) to give accurate, context-aware replies — not generic chatbot fluff.', NULL, 'Learn More', '#features', NULL, NULL, 5),
('integrations', 'Plays well with your stack', 'Built on open standards. Connect to the tools you already use.', NULL, NULL, NULL, NULL, NULL, 6),
('pricing', 'Simple, transparent pricing', 'Start free. Scale as you grow. No per-seat AI fees.', NULL, NULL, NULL, NULL, NULL, 7),
('testimonials', 'Loved by teams worldwide', 'See what our customers have to say about Replai.', NULL, NULL, NULL, NULL, NULL, 8),
('cta_banner', 'Ready to transform your WhatsApp sales?', 'Join 500+ businesses using Replai to engage customers, close deals, and automate conversations.', NULL, 'Get Started Free', '/signup', NULL, NULL, 9)
ON CONFLICT (section_key) DO NOTHING;

-- Features
INSERT INTO landing_features (icon_name, title, description, position) VALUES
('MessageSquare', 'Shared Team Inbox', 'Multiple agents, one WhatsApp number. Assign conversations, track status, add internal notes. Never miss a customer message.', 1),
('Bot', 'AI Reply Assistant', 'AI-drafted replies powered by OpenAI, Anthropic, or Gemini. Add a knowledge base (FAQs, docs) and the AI answers from your own content.', 2),
('Workflow', 'Visual Automations', 'No-code automation builder with triggers, conditions, delays, webhooks, and tag management. Build complex workflows visually.', 3),
('Send', 'Broadcast Campaigns', 'Send Meta-approved template messages to thousands. Track delivery, read, and reply rates in real-time.', 4),
('Kanban', 'Sales Pipelines', 'Kanban deal boards linked to conversations. Track deal value, stages, and expected close dates.', 5),
('Users', 'Contact Management', 'Tags, custom fields, CSV import, phone deduplication, and full conversation history per contact.', 6)
ON CONFLICT DO NOTHING;

-- Pricing tiers
INSERT INTO landing_pricing_tiers (name, price_monthly, price_yearly, price_subtitle, features, is_highlighted, cta_text, position) VALUES
('Starter', '$29', '$290', 'per month', '["Up to 1,000 contacts", "2 team members", "Basic automations", "5,000 messages/month", "Email support", "Community access"]', FALSE, 'Get Started', 1),
('Professional', '$79', '$790', 'per month', '["Up to 10,000 contacts", "10 team members", "Advanced automations & flows", "25,000 messages/month", "AI reply assistant", "Knowledge base (RAG)", "Priority support", "API access"]', TRUE, 'Start Free Trial', 2),
('Enterprise', 'Custom', 'Custom', 'contact us', '["Unlimited contacts", "Unlimited team members", "All automations & flows", "Unlimited messages", "Multi-provider AI (OpenAI, Anthropic, Gemini)", "Dedicated account manager", "SLA guarantee", "Custom integrations", "MCP server access"]', FALSE, 'Contact Sales', 3)
ON CONFLICT DO NOTHING;

-- Testimonials
INSERT INTO landing_testimonials (quote, author_name, author_role, author_company, rating, position) VALUES
('Replai transformed how we handle customer support. AI replies save our team 4 hours every day, and the shared inbox means nothing falls through the cracks.', 'Sarah Chen', 'Head of Customer Success', 'TechStart Solutions', 5, 1),
('We switched from 3 separate tools to just Replai. The automation builder alone paid for itself in the first week.', 'Marcus Johnson', 'CEO', 'GreenLeaf Commerce', 5, 2),
('The knowledge base feature is incredible. Our AI assistant actually answers questions accurately because it reads from our own product docs.', 'Priya Patel', 'Operations Manager', 'FastTrack Logistics', 5, 3)
ON CONFLICT DO NOTHING;

-- Integrations
INSERT INTO landing_integrations (name, description, position) VALUES
('WhatsApp Business API', 'Official Meta Cloud API integration', 1),
('Supabase', 'PostgreSQL database with real-time subscriptions', 2),
('OpenAI', 'GPT-4 powered AI reply generation', 3),
('Anthropic', 'Claude AI for intelligent responses', 4),
('Google Gemini', 'Gemini AI provider support', 5),
('Webhooks', 'Send data to any external service', 6),
('REST API', 'Full public API with scoped keys', 7),
('MCP Protocol', 'Drive your CRM from AI assistants', 8)
ON CONFLICT DO NOTHING;

-- Legal pages
INSERT INTO legal_pages (slug, title, content_markdown) VALUES
('privacy-policy', 'Privacy Policy', '# Privacy Policy\n\n**Last updated: July 29, 2026**\n\n## 1. Introduction\n\nReplai (operated by Junkies Coder) respects your privacy. This policy explains how we collect, use, and protect your data when you use our WhatsApp CRM platform.\n\n## 2. Information We Collect\n\n### Account Information\n- Name and email address provided during registration\n- Password (stored hashed, never in plaintext)\n- Profile avatar (optional)\n\n### WhatsApp Business API Data\n- Messages sent and received through the platform\n- Contact information (phone numbers, names)\n- Conversation metadata (timestamps, status)\n- Template message content and delivery status\n\n### Usage Analytics\n- Feature usage patterns\n- Login timestamps and session duration\n- Browser and device information\n\n## 3. How We Use Your Information\n\n- Providing CRM services (inbox, contacts, pipelines, broadcasts)\n- Processing WhatsApp messages on your behalf\n- AI-powered features (reply generation, knowledge base queries)\n- Platform analytics and improvement\n- Security monitoring and fraud prevention\n\n## 4. Data Storage & Security\n\n- AES-256-GCM encryption for API tokens at rest\n- Supabase PostgreSQL with Row-Level Security (RLS)\n- HMAC-SHA256 webhook signature verification\n- TLS 1.3 encryption for all data in transit\n- Rate limiting on all API endpoints\n\n## 5. Third-Party Services\n\n- **Meta** — WhatsApp Business API (message delivery)\n- **Supabase** — Database hosting and authentication\n- **AI Providers** — OpenAI, Anthropic, Google (only when configured by you using your own API keys)\n\n## 6. Data Retention\n\nMessage history and account data are retained while your account is active. Upon account deletion, all associated data is permanently removed within 30 days.\n\n## 7. Your Rights\n\n- **Access** — Request a copy of your personal data\n- **Correction** — Update inaccurate information\n- **Deletion** — Request account and data deletion\n- **Data Portability** — Export your data in standard formats\n- **Opt-out** — Disable AI processing for your conversations\n\n## 8. WhatsApp Business API Compliance\n\nWe comply with Meta''s Business Messaging policies and WhatsApp Business Terms of Service. All template messages require Meta approval before sending.\n\n## 9. Children''s Privacy\n\nReplai is not intended for users under 18 years of age.\n\n## 10. Changes to This Policy\n\nWe may update this policy periodically. Users will be notified via email of significant changes.\n\n## 11. Contact Us\n\nFor privacy inquiries: privacy@junkiescoder.com'),
('terms-of-service', 'Terms of Service', '# Terms of Service\n\n**Effective Date: July 29, 2026**\n\n## 1. Acceptance of Terms\n\nBy using Replai, you agree to these Terms of Service.\n\n## 2. Description of Service\n\nReplai provides a self-hosted WhatsApp CRM platform with shared inbox, AI replies, automations, broadcasts, sales pipelines, and contact management.\n\n## 3. Account Registration & Security\n\nYou must provide accurate information during registration, maintain password security, and are responsible for all activity under your account.\n\n## 4. Acceptable Use\n\nYou must not send spam, violate WhatsApp policies, use the service for illegal purposes, or attempt to reverse-engineer the platform.\n\n## 5. WhatsApp Business API Compliance\n\nYou must comply with Meta''s Commerce Policy, Business Messaging guidelines, and maintain a valid WhatsApp Business Account.\n\n## 6. AI Features Disclaimer\n\nAI-generated replies are suggestions only. You are responsible for reviewing all AI outputs before sending to customers. Replai is not liable for AI-generated content.\n\n## 7. Data Ownership\n\nYou retain full ownership of your data (contacts, messages, templates). Replai does not sell or share user data with third parties.\n\n## 8. Service Availability\n\nWe provide best-effort uptime with no guaranteed SLA for self-hosted deployments.\n\n## 9. Intellectual Property\n\nReplai branding, documentation, and code are property of Junkies Coder (MIT licensed).\n\n## 10. Limitation of Liability\n\nReplai is provided "as is" without warranty. We are not liable for indirect, incidental, or consequential damages.\n\n## 11. Termination\n\nEither party may terminate. User data will be deleted within 30 days of account closure.\n\n## 12. Governing Law\n\nThese terms are governed by applicable local laws.\n\n## 13. Contact\n\nFor legal inquiries: legal@junkiescoder.com'),
('data-processing-agreement', 'Data Processing Agreement', '# Data Processing Agreement\n\n**Effective Date: July 29, 2026**\n\n## 1. Definitions\n\n- **Data Controller**: The customer using Replai\n- **Data Processor**: Replai (Junkies Coder)\n- **Personal Data**: Any data relating to identified individuals\n- **Processing**: Any operation performed on personal data\n\n## 2. Scope & Purpose\n\nThis DPA governs how Replai processes personal data on behalf of the customer as part of providing WhatsApp CRM services.\n\n## 3. Data Processing Details\n\n**Types of data processed:**\n- WhatsApp messages and conversation metadata\n- Contact information (phone numbers, names, emails)\n- AI interaction logs (when AI features are enabled)\n- User account and authentication data\n\n## 4. Security Measures\n\n- AES-256-GCM encryption at rest for sensitive tokens\n- TLS 1.3 encryption in transit\n- Row-Level Security (RLS) database isolation per account\n- HMAC-SHA256 webhook verification\n- Rate limiting on all endpoints\n\n## 5. Sub-processors\n\n- **Supabase** — Database hosting and authentication\n- **Meta** — WhatsApp Business API\n- **AI Providers** — Only when configured by customer using their own keys\n\n## 6. Data Retention & Deletion\n\nData is retained during active subscription and deleted within 30 days of account termination.\n\n## 7. Contact\n\nFor DPA inquiries: dpa@junkiescoder.com'),
('cookie-policy', 'Cookie Policy', '# Cookie Policy\n\n**Last updated: July 29, 2026**\n\n## 1. What Are Cookies\n\nCookies are small text files stored on your device when you visit our platform.\n\n## 2. How We Use Cookies\n\n- **Essential cookies** — Authentication and session management\n- **Functional cookies** — User preferences and theme settings\n- **Analytics cookies** — Usage tracking for platform improvement\n\n## 3. Types of Cookies We Use\n\n| Cookie Name | Purpose | Duration | Type |\n|---|---|---|---|\n| sb-auth-token | Supabase authentication session | Session | Essential |\n| theme | User theme preference | 1 year | Functional |\n| locale | User language preference | 1 year | Functional |\n\n## 4. Third-Party Cookies\n\nWe do not use third-party advertising cookies. Supabase may set cookies for authentication.\n\n## 5. Managing Cookies\n\nYou can manage cookies through your browser settings. Disabling essential cookies may affect platform functionality.\n\n## 6. Contact\n\nFor cookie inquiries: privacy@junkiescoder.com'),
('acceptable-use-policy', 'Acceptable Use Policy', '# Acceptable Use Policy\n\n**Effective Date: July 29, 2026**\n\n## 1. Purpose\n\nThis policy defines acceptable behavior when using Replai to send WhatsApp messages.\n\n## 2. Prohibited Activities\n\n- Sending unsolicited bulk messages (spam)\n- Sending messages without proper opt-in consent\n- Distributing malware, phishing links, or harmful content\n- Impersonating other businesses or individuals\n- Violating Meta''s WhatsApp Business Policy\n- Using AI features to generate misleading or illegal content\n- Attempting to circumvent rate limits or security measures\n- Harvesting contact data without consent\n\n## 3. WhatsApp Compliance\n\nYou must follow Meta''s 24-hour messaging window rules, use approved templates for outbound messages, and maintain acceptable quality ratings.\n\n## 4. AI Usage Guidelines\n\n- Review all AI replies before sending to customers\n- Do not rely solely on AI for sensitive communications\n- Keep knowledge base content accurate and current\n\n## 5. Enforcement\n\nViolations may result in account suspension or permanent ban.\n\n## 6. Contact\n\nReport violations: abuse@junkiescoder.com')
ON CONFLICT (slug) DO NOTHING;
