-- Starter templates, part 1 of 2. Generated by scripts/generate-library-seed.mjs.
--
-- Written to PASS META REVIEW, which is stricter about wording than about
-- structure. Two rules drive every choice here:
--
--   * UTILITY must be transactional — about an order, account or booking the
--     customer already has. One promotional sentence in a utility template gets
--     it reclassified as marketing, which changes what it costs to send.
--   * Every variable ships with a REALISTIC sample value. Vague samples
--     ("test", "abc") are one of the most common rejection reasons, so the
--     library never leaves an operator to invent them.
--
-- Variables are contiguous from {{1}} — Meta rejects gaps — and footers carry no
-- variables, which Meta also forbids.
--
-- Idempotent on slug, so re-running refreshes the shipped copy without
-- duplicating rows and without touching templates an operator added themselves.

INSERT INTO template_library_templates (
  category_id, slug, title, description, emoji, meta_category, template_type, language,
  header_type, header_content, body_text, footer_text, buttons, sample_values, tags, position
)
SELECT c.id, v.slug, v.title, v.description, v.emoji, v.meta_category, v.template_type, v.language,
       v.header_type, v.header_content, v.body_text, v.footer_text, v.buttons, v.sample_values,
       v.tags, v.position
FROM (VALUES

($t$ecommerce$t$, $t$ec-order-confirmation$t$, $t$Order Confirmation$t$, $t$Instant confirmation with order value and delivery estimate.$t$, $t$✅$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Order Confirmed$t$,
 $t$Hi {{1}}!

Great news — your order *{{2}}* is confirmed and we are preparing it with care.

💰 Order value: {{3}}
📅 Expected delivery: {{4}}

You will receive tracking details shortly. Thank you for shopping with us!$t$,
 $t$Questions? Just reply to this message$t$, $t$[{"url":"https://example.com/orders/{{1}}","text":"View Order","type":"URL","example":"10234"},{"text":"Need Help","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rahul","#10234","₹2,499","18 August"],"header":[]}$t$::jsonb, ARRAY[$t$order$t$,$t$confirmation$t$]::text[], 10),

($t$ecommerce$t$, $t$ec-shipping-update$t$, $t$Shipping Update$t$, $t$Tell customers their parcel is on the way, with tracking.$t$, $t$🚚$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Your Order Has Shipped$t$,
 $t$Hi {{1}}!

Your order *{{2}}* has shipped and is on its way to you.

📦 Tracking number: {{3}}
🚚 Courier: {{4}}
📅 Estimated arrival: {{5}}$t$,
 $t$Safe delivery guaranteed$t$, $t$[{"url":"https://example.com/track/{{1}}","text":"Track Package","type":"URL","example":"AWB123456789"},{"text":"Delivery Instructions","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rahul","#10234","AWB123456789","Delhivery","20 August"],"header":[]}$t$::jsonb, ARRAY[$t$shipping$t$,$t$tracking$t$]::text[], 20),

($t$ecommerce$t$, $t$ec-delivered$t$, $t$Delivery Confirmation$t$, $t$Confirm delivery and invite a review.$t$, $t$📦$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}}, your order *{{2}}* was delivered on {{3}}.

We hope you love it! If anything is not right, reply here and we will sort it out.$t$,
 $t$Thank you for shopping with us$t$, $t$[{"text":"Rate My Order","type":"QUICK_REPLY"},{"text":"Report An Issue","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rahul","#10234","20 August"],"header":[]}$t$::jsonb, ARRAY[$t$delivery$t$,$t$feedback$t$]::text[], 30),

($t$ecommerce$t$, $t$ec-cart-abandonment$t$, $t$Cart Abandonment Recovery$t$, $t$Bring back shoppers who left items behind.$t$, $t$🛒$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}}, you left something in your cart! 🛒

*{{2}}* is still waiting for you, but stock is limited.

Complete your order now and get {{3}} off with code *{{4}}*.$t$,
 $t$Offer valid for a limited time$t$, $t$[{"url":"https://example.com/cart","text":"Complete Order","type":"URL","example":""},{"text":"Copy Code","type":"COPY_CODE","example":"SAVE10"}]$t$::jsonb, $t${"body":["Rahul","Wireless Earbuds","10%","SAVE10"],"header":[]}$t$::jsonb, ARRAY[$t$cart$t$,$t$recovery$t$,$t$promo$t$]::text[], 40),

($t$ecommerce$t$, $t$ec-mega-sale$t$, $t$Mega Sale Announcement$t$, $t$High-converting sale announcement with a deadline.$t$, $t$🔥$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Mega Sale Is Live$t$,
 $t$Hi {{1}}! 🔥

Our biggest sale of the season is here — up to *{{2}} off* across {{3}}.

Use code *{{4}}* at checkout. Sale ends {{5}}!$t$,
 $t$Limited stock. Terms apply.$t$, $t$[{"url":"https://example.com/sale","text":"Shop Now","type":"URL","example":""},{"text":"Copy Code","type":"COPY_CODE","example":"MEGA50"}]$t$::jsonb, $t${"body":["Rahul","50%","all categories","MEGA50","31 August"],"header":[]}$t$::jsonb, ARRAY[$t$sale$t$,$t$promo$t$]::text[], 50),

($t$ecommerce$t$, $t$ec-back-in-stock$t$, $t$Back In Stock Alert$t$, $t$Notify customers a wishlisted product returned.$t$, $t$🔔$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Good news {{1}}! 🎉

*{{2}}* is back in stock and available in your size.

It sold out fast last time, so grab yours before it goes again.$t$,
 $t$While stocks last$t$, $t$[{"url":"https://example.com/p/{{1}}","text":"Buy Now","type":"URL","example":"wireless-earbuds"},{"text":"Notify Me Later","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rahul","Wireless Earbuds"],"header":[]}$t$::jsonb, ARRAY[$t$restock$t$,$t$alert$t$]::text[], 60),

($t$education$t$, $t$ed-admission-confirmed$t$, $t$Admission Confirmation$t$, $t$Confirm a seat with course and joining details.$t$, $t$🎓$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Admission Confirmed$t$,
 $t$Congratulations {{1}}! 🎓

Your admission to *{{2}}* for the {{3}} batch is confirmed.

🆔 Enrolment number: {{4}}
📅 Classes begin: {{5}}

We look forward to welcoming you.$t$,
 $t$Reply here for any questions$t$, $t$[{"url":"https://example.com/admission/{{1}}","text":"View Details","type":"URL","example":"ENR2026118"},{"text":"Talk To Counsellor","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Ananya","B.Sc Computer Science","2026","ENR2026118","1 September"],"header":[]}$t$::jsonb, ARRAY[$t$admission$t$,$t$enrolment$t$]::text[], 10),

($t$education$t$, $t$ed-fee-reminder$t$, $t$Fee Payment Reminder$t$, $t$Polite reminder before a fee deadline.$t$, $t$💳$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Fee Payment Reminder$t$,
 $t$Dear {{1}},

This is a reminder that the {{2}} fee of *{{3}}* for {{4}} is due on *{{5}}*.

Please complete the payment to avoid a late fee.$t$,
 $t$Ignore if already paid$t$, $t$[{"url":"https://example.com/fees/{{1}}","text":"Pay Now","type":"URL","example":"ENR2026118"},{"text":"Payment Help","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Ananya","second term","₹18,000","B.Sc Computer Science","25 August"],"header":[]}$t$::jsonb, ARRAY[$t$fees$t$,$t$reminder$t$]::text[], 20),

($t$education$t$, $t$ed-class-schedule$t$, $t$Class Schedule Update$t$, $t$Send a timetable change or new schedule.$t$, $t$📅$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

There is an update to your class schedule for {{2}}.

📚 Subject: {{3}}
🕐 New timing: {{4}}
📍 Venue: {{5}}

Please plan accordingly.$t$,
 NULL, $t$[{"text":"Got It","type":"QUICK_REPLY"},{"text":"I Have A Conflict","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Ananya","this week","Data Structures","Mon & Wed, 10:00 AM","Room 204"],"header":[]}$t$::jsonb, ARRAY[$t$schedule$t$,$t$timetable$t$]::text[], 30),

($t$education$t$, $t$ed-result-published$t$, $t$Result Published$t$, $t$Tell a student their result is available.$t$, $t$📊$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Results Are Out$t$,
 $t$Hi {{1}},

Your {{2}} results have been published.

🆔 Roll number: {{3}}
📊 Result status: {{4}}

Log in to view your detailed marksheet.$t$,
 $t$Congratulations on your hard work$t$, $t$[{"url":"https://example.com/results/{{1}}","text":"View Result","type":"URL","example":"ENR2026118"}]$t$::jsonb, $t${"body":["Ananya","semester 3","ENR2026118","Passed with distinction"],"header":[]}$t$::jsonb, ARRAY[$t$results$t$,$t$exam$t$]::text[], 40),

($t$education$t$, $t$ed-course-launch$t$, $t$New Course Launch$t$, $t$Promote a new batch or course.$t$, $t$🚀$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$New Batch Starting$t$,
 $t$Hi {{1}}! 🚀

Admissions are open for our new *{{2}}* batch starting {{3}}.

✅ {{4}}
🎯 Early-bird discount: {{5}} off

Seats are limited — book your place today.$t$,
 $t$Talk to us for a free counselling call$t$, $t$[{"url":"https://example.com/courses","text":"Enrol Now","type":"URL","example":""},{"text":"Call Us","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Ananya","Full-Stack Development","1 September","Live classes with placement support","20%"],"header":[]}$t$::jsonb, ARRAY[$t$course$t$,$t$promo$t$]::text[], 50),

($t$healthcare$t$, $t$hc-appointment-confirmed$t$, $t$Appointment Confirmation$t$, $t$Confirm a booking with doctor, date and place.$t$, $t$🏥$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Appointment Confirmed$t$,
 $t$Hello {{1}},

Your appointment is confirmed.

👨‍⚕️ Doctor: {{2}}
📅 Date & time: {{3}}
📍 Clinic: {{4}}
🆔 Booking ID: {{5}}

Please arrive 10 minutes early.$t$,
 $t$Reply to reschedule$t$, $t$[{"text":"Confirm","type":"QUICK_REPLY"},{"text":"Reschedule","type":"QUICK_REPLY"},{"text":"Cancel","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Meera","Dr. S. Kulkarni","18 August, 11:30 AM","Sunrise Clinic, Pune","APT-4471"],"header":[]}$t$::jsonb, ARRAY[$t$appointment$t$,$t$booking$t$]::text[], 10),

($t$healthcare$t$, $t$hc-appointment-reminder$t$, $t$Appointment Reminder$t$, $t$Reduce no-shows with a day-before nudge.$t$, $t$⏰$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hello {{1}},

This is a reminder of your appointment with *{{2}}* tomorrow at *{{3}}*.

📍 {{4}}

Please bring any previous reports with you.$t$,
 $t$Reply to reschedule$t$, $t$[{"text":"I Will Be There","type":"QUICK_REPLY"},{"text":"Reschedule","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Meera","Dr. S. Kulkarni","11:30 AM","Sunrise Clinic, Pune"],"header":[]}$t$::jsonb, ARRAY[$t$reminder$t$,$t$appointment$t$]::text[], 20),

($t$healthcare$t$, $t$hc-report-ready$t$, $t$Lab Report Ready$t$, $t$Tell a patient their report is available.$t$, $t$🧪$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Your Report Is Ready$t$,
 $t$Hello {{1}},

Your {{2}} report from {{3}} is now ready.

🆔 Reference: {{4}}

You can download it securely using the link below.$t$,
 $t$Contact us to discuss your results$t$, $t$[{"url":"https://example.com/reports/{{1}}","text":"Download Report","type":"URL","example":"LAB-99871"},{"text":"Call Clinic","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Meera","blood test","14 August","LAB-99871"],"header":[]}$t$::jsonb, ARRAY[$t$reports$t$,$t$lab$t$]::text[], 30),

($t$healthcare$t$, $t$hc-medicine-reminder$t$, $t$Prescription Refill Reminder$t$, $t$Remind a patient to refill medication.$t$, $t$💊$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hello {{1}},

Your prescription for *{{2}}* is due for a refill on {{3}}.

Reply here and we will have it ready for pickup, or arrange delivery.$t$,
 $t$Take care$t$, $t$[{"text":"Refill Now","type":"QUICK_REPLY"},{"text":"Remind Me Later","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Meera","Thyronorm 50mcg","20 August"],"header":[]}$t$::jsonb, ARRAY[$t$prescription$t$,$t$refill$t$]::text[], 40),

($t$healthcare$t$, $t$hc-health-checkup$t$, $t$Health Checkup Camp$t$, $t$Promote a preventive checkup package.$t$, $t$❤️$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Annual Health Checkup$t$,
 $t$Hi {{1}}! ❤️

Our {{2}} health checkup package is available at *{{3}}* until {{4}}.

Includes {{5}}. Early detection makes all the difference.$t$,
 $t$Book a slot that suits you$t$, $t$[{"url":"https://example.com/checkup","text":"Book Checkup","type":"URL","example":""},{"text":"Call Us","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Meera","full-body","₹1,999","31 August","45 tests and a doctor consultation"],"header":[]}$t$::jsonb, ARRAY[$t$checkup$t$,$t$promo$t$]::text[], 50),

($t$real-estate$t$, $t$re-site-visit-confirmed$t$, $t$Site Visit Confirmation$t$, $t$Confirm a property visit with directions.$t$, $t$🏠$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Site Visit Confirmed$t$,
 $t$Hi {{1}},

Your site visit is confirmed.

🏠 Property: {{2}}
📅 Date & time: {{3}}
📍 Meeting point: {{4}}
👤 Your host: {{5}}

We look forward to showing you around.$t$,
 $t$Reply to reschedule$t$, $t$[{"url":"https://example.com/site/{{1}}","text":"Get Directions","type":"URL","example":"skyline-residency"},{"text":"Reschedule","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Vikram","Skyline Residency, 3BHK","17 August, 4:00 PM","Skyline Sales Office, Baner","Amit (Sales)"],"header":[]}$t$::jsonb, ARRAY[$t$sitevisit$t$,$t$property$t$]::text[], 10),

($t$real-estate$t$, $t$re-new-listing$t$, $t$New Property Listing$t$, $t$Share a new listing matching a buyer brief.$t$, $t$🔑$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$New Listing For You$t$,
 $t$Hi {{1}}! 🔑

A new property matching your requirements is available.

🏠 {{2}}
📍 {{3}}
💰 {{4}}
📐 {{5}}

Interested? Let us arrange a visit.$t$,
 $t$More options available on request$t$, $t$[{"url":"https://example.com/listing/{{1}}","text":"View Property","type":"URL","example":"skyline-3bhk"},{"text":"Book Site Visit","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Vikram","3BHK Apartment","Baner, Pune","₹1.15 Cr onwards","1,450 sq ft"],"header":[]}$t$::jsonb, ARRAY[$t$listing$t$,$t$property$t$]::text[], 20),

($t$real-estate$t$, $t$re-payment-milestone$t$, $t$Payment Milestone Due$t$, $t$Remind a buyer of a construction-linked payment.$t$, $t$💳$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Payment Milestone Due$t$,
 $t$Dear {{1}},

The *{{2}}* milestone for your unit {{3}} is now due.

💰 Amount: {{4}}
📅 Due date: {{5}}

Please arrange the payment to keep your schedule on track.$t$,
 $t$Contact us for a payment plan$t$, $t$[{"url":"https://example.com/account/{{1}}","text":"View Statement","type":"URL","example":"SKY-A-1204"},{"text":"Call Accounts","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Vikram","slab completion","A-1204","₹8,50,000","25 August"],"header":[]}$t$::jsonb, ARRAY[$t$payment$t$,$t$milestone$t$]::text[], 30),

($t$real-estate$t$, $t$re-document-request$t$, $t$Document Request$t$, $t$Ask a buyer for pending paperwork.$t$, $t$📄$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

To proceed with your booking for {{2}}, we need the following document: *{{3}}*.

Please share it by {{4}} so we can complete the registration on time.$t$,
 $t$Reply with the document attached$t$, $t$[{"text":"Send Now","type":"QUICK_REPLY"},{"text":"Need Help","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Vikram","unit A-1204","PAN card copy","20 August"],"header":[]}$t$::jsonb, ARRAY[$t$documents$t$,$t$kyc$t$]::text[], 40),

($t$travel$t$, $t$tr-booking-confirmed$t$, $t$Booking Confirmation$t$, $t$Confirm a trip with reference and dates.$t$, $t$✈️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Booking Confirmed$t$,
 $t$Hi {{1}}! ✈️

Your booking is confirmed.

🆔 Reference: {{2}}
📍 Destination: {{3}}
📅 Travel dates: {{4}}
👥 Travellers: {{5}}

Your detailed itinerary follows shortly.$t$,
 $t$Happy travels!$t$, $t$[{"url":"https://example.com/booking/{{1}}","text":"View Itinerary","type":"URL","example":"TRV88213"},{"text":"Contact Support","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Sneha","TRV88213","Bali, Indonesia","12–19 September","2 adults"],"header":[]}$t$::jsonb, ARRAY[$t$booking$t$,$t$travel$t$]::text[], 10),

($t$travel$t$, $t$tr-checkin-reminder$t$, $t$Check-in Reminder$t$, $t$Nudge travellers to check in on time.$t$, $t$🧳$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

Your flight {{2}} to {{3}} departs on *{{4}}*. Online check-in is now open.

Please check in and carry a valid photo ID.$t$,
 $t$Safe journey$t$, $t$[{"url":"https://example.com/checkin/{{1}}","text":"Check In","type":"URL","example":"TRV88213"},{"text":"Need Assistance","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Sneha","AI-634","Bali","12 September, 6:40 AM"],"header":[]}$t$::jsonb, ARRAY[$t$checkin$t$,$t$flight$t$]::text[], 20),

($t$travel$t$, $t$tr-holiday-package$t$, $t$Holiday Package Offer$t$, $t$Promote a seasonal package.$t$, $t$🏝️$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Holiday Offer$t$,
 $t$Hi {{1}}! 🏝️

Our *{{2}}* package is now available from *{{3}}* per person.

✅ {{4}}
📅 Valid for travel until {{5}}

Limited seats at this price.$t$,
 $t$Terms and conditions apply$t$, $t$[{"url":"https://example.com/packages","text":"View Package","type":"URL","example":""},{"text":"Call To Book","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Sneha","5-night Bali","₹42,999","Flights, hotel, breakfast and transfers","31 December"],"header":[]}$t$::jsonb, ARRAY[$t$package$t$,$t$promo$t$]::text[], 30),

($t$travel$t$, $t$tr-trip-feedback$t$, $t$Post-Trip Feedback$t$, $t$Ask for a review after travel.$t$, $t$⭐$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

Welcome back! We hope your trip to {{2}} was wonderful.

Would you share a quick word about your experience? It helps us and other travellers.$t$,
 $t$Thank you for travelling with us$t$, $t$[{"text":"Leave Feedback","type":"QUICK_REPLY"},{"text":"Maybe Later","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Sneha","Bali"],"header":[]}$t$::jsonb, ARRAY[$t$feedback$t$,$t$review$t$]::text[], 40),

($t$automotive$t$, $t$au-test-drive$t$, $t$Test Drive Confirmation$t$, $t$Confirm a test drive slot.$t$, $t$🚗$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Test Drive Confirmed$t$,
 $t$Hi {{1}}! 🚗

Your test drive is booked.

🚙 Model: {{2}}
📅 Date & time: {{3}}
📍 Showroom: {{4}}

Please bring your driving licence.$t$,
 $t$Reply to reschedule$t$, $t$[{"text":"Confirm","type":"QUICK_REPLY"},{"text":"Reschedule","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Arjun","Creta SX (Diesel)","17 August, 12:00 PM","Prime Motors, Kothrud"],"header":[]}$t$::jsonb, ARRAY[$t$testdrive$t$,$t$showroom$t$]::text[], 10),

($t$automotive$t$, $t$au-service-reminder$t$, $t$Service Due Reminder$t$, $t$Remind an owner their service is due.$t$, $t$🔧$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Service Due$t$,
 $t$Hi {{1}},

Your {{2}} ({{3}}) is due for its {{4}} service on *{{5}}*.

Book a slot and we will keep it ready for you.$t$,
 $t$Free pickup and drop available$t$, $t$[{"url":"https://example.com/service/{{1}}","text":"Book Service","type":"URL","example":"MH12AB1234"},{"text":"Call Service","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Arjun","Creta","MH12AB1234","30,000 km","22 August"],"header":[]}$t$::jsonb, ARRAY[$t$service$t$,$t$reminder$t$]::text[], 20),

($t$automotive$t$, $t$au-delivery-ready$t$, $t$Vehicle Ready For Delivery$t$, $t$Tell a buyer their vehicle is ready.$t$, $t$🎉$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Your Car Is Ready$t$,
 $t$Congratulations {{1}}! 🎉

Your *{{2}}* is ready for delivery.

📅 Delivery slot: {{3}}
📍 Showroom: {{4}}
🆔 Booking ID: {{5}}

Please carry the original documents.$t$,
 $t$We cannot wait to hand over the keys$t$, $t$[{"text":"Confirm Slot","type":"QUICK_REPLY"},{"text":"Request Change","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Arjun","Creta SX Diesel","19 August, 11:00 AM","Prime Motors, Kothrud","BK-77210"],"header":[]}$t$::jsonb, ARRAY[$t$delivery$t$,$t$handover$t$]::text[], 30),

($t$automotive$t$, $t$au-insurance-renewal$t$, $t$Insurance Renewal Due$t$, $t$Remind an owner to renew cover.$t$, $t$🛡️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

The insurance for your {{2}} ({{3}}) expires on *{{4}}*.

Renew before the expiry date to keep your no-claim bonus of {{5}}.$t$,
 $t$Driving uninsured is an offence$t$, $t$[{"url":"https://example.com/renew/{{1}}","text":"Renew Now","type":"URL","example":"MH12AB1234"},{"text":"Get A Quote","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Arjun","Creta","MH12AB1234","28 August","50%"],"header":[]}$t$::jsonb, ARRAY[$t$insurance$t$,$t$renewal$t$]::text[], 40),

($t$automotive$t$, $t$au-exchange-offer$t$, $t$Exchange Offer$t$, $t$Promote an exchange or upgrade event.$t$, $t$💰$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Exchange Bonanza$t$,
 $t$Hi {{1}}! 💰

Upgrade your {{2}} this month and get up to *{{3}}* exchange bonus plus {{4}}.

Offer valid until {{5}}. Free valuation at the showroom.$t$,
 $t$Terms and conditions apply$t$, $t$[{"url":"https://example.com/exchange","text":"Book Valuation","type":"URL","example":""},{"text":"Call Us","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Arjun","current car","₹60,000","a free accessory kit","31 August"],"header":[]}$t$::jsonb, ARRAY[$t$exchange$t$,$t$promo$t$]::text[], 50),

($t$bfsi$t$, $t$bf-payment-reminder$t$, $t$EMI Payment Reminder$t$, $t$Remind a customer before an EMI date.$t$, $t$💳$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Payment Reminder$t$,
 $t$Dear {{1}},

Your EMI of *{{2}}* for loan account {{3}} is due on *{{4}}*.

Please maintain sufficient balance to avoid a late payment charge.$t$,
 $t$Ignore if already paid$t$, $t$[{"url":"https://example.com/pay/{{1}}","text":"Pay Now","type":"URL","example":"LN889221"},{"text":"Payment Help","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mr. Sharma","₹14,250","LN889221","5 September"],"header":[]}$t$::jsonb, ARRAY[$t$emi$t$,$t$reminder$t$]::text[], 10),

($t$bfsi$t$, $t$bf-payment-received$t$, $t$Payment Received$t$, $t$Confirm a payment was credited.$t$, $t$✅$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Dear {{1}},

We have received your payment of *{{2}}* towards {{3}} on {{4}}.

🆔 Transaction reference: {{5}}

Thank you.$t$,
 $t$This is a system generated confirmation$t$, $t$[{"url":"https://example.com/receipt/{{1}}","text":"View Receipt","type":"URL","example":"TXN5540921"}]$t$::jsonb, $t${"body":["Mr. Sharma","₹14,250","loan account LN889221","5 September","TXN5540921"],"header":[]}$t$::jsonb, ARRAY[$t$payment$t$,$t$receipt$t$]::text[], 20),

($t$bfsi$t$, $t$bf-policy-renewal$t$, $t$Policy Renewal Due$t$, $t$Remind a policyholder to renew.$t$, $t$🛡️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Policy Renewal Due$t$,
 $t$Dear {{1}},

Your {{2}} policy {{3}} expires on *{{4}}*.

Renew now to continue your cover of {{5}} without a break.$t$,
 $t$Cover lapses if not renewed$t$, $t$[{"url":"https://example.com/policy/{{1}}","text":"Renew Policy","type":"URL","example":"POL77120"},{"text":"Talk To Advisor","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Mr. Sharma","health insurance","POL77120","30 August","₹10 lakh"],"header":[]}$t$::jsonb, ARRAY[$t$policy$t$,$t$renewal$t$]::text[], 30),

($t$bfsi$t$, $t$bf-kyc-pending$t$, $t$KYC Pending$t$, $t$Ask a customer to complete verification.$t$, $t$🪪$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Dear {{1}},

Your KYC verification for account {{2}} is still pending.

Please complete it by *{{3}}* to keep your account fully active.$t$,
 $t$Never share your OTP with anyone$t$, $t$[{"url":"https://example.com/kyc/{{1}}","text":"Complete KYC","type":"URL","example":"AC99120"},{"text":"Need Help","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mr. Sharma","AC99120","20 August"],"header":[]}$t$::jsonb, ARRAY[$t$kyc$t$,$t$compliance$t$]::text[], 40),

($t$bfsi$t$, $t$bf-statement-ready$t$, $t$Account Statement Ready$t$, $t$Tell a customer their statement is available.$t$, $t$📄$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Dear {{1}},

Your account statement for *{{2}}* is now available.

🆔 Account: {{3}}
💰 Closing balance: {{4}}$t$,
 $t$Download securely from your dashboard$t$, $t$[{"url":"https://example.com/statement/{{1}}","text":"View Statement","type":"URL","example":"AC99120"}]$t$::jsonb, $t${"body":["Mr. Sharma","July 2026","AC99120","₹1,24,530"],"header":[]}$t$::jsonb, ARRAY[$t$statement$t$,$t$account$t$]::text[], 50),

($t$logistics$t$, $t$lg-pickup-confirmed$t$, $t$Pickup Confirmed$t$, $t$Confirm a scheduled pickup.$t$, $t$📦$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Pickup Scheduled$t$,
 $t$Hi {{1}},

Your pickup is scheduled.

🆔 Consignment: {{2}}
📅 Pickup window: {{3}}
📍 Address: {{4}}

Please keep the parcel packed and ready.$t$,
 $t$Reply to reschedule$t$, $t$[{"text":"Confirm","type":"QUICK_REPLY"},{"text":"Reschedule","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Ravi","CN-4471902","17 August, 10 AM – 1 PM","Flat 402, Green Meadows, Pune"],"header":[]}$t$::jsonb, ARRAY[$t$pickup$t$,$t$consignment$t$]::text[], 10),

($t$logistics$t$, $t$lg-out-for-delivery$t$, $t$Out For Delivery$t$, $t$Tell a customer the parcel is arriving today.$t$, $t$🚚$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

Your parcel *{{2}}* is out for delivery today and should arrive between *{{3}}*.

🧑‍✈️ Delivery agent: {{4}}$t$,
 $t$Please keep your phone reachable$t$, $t$[{"url":"https://example.com/track/{{1}}","text":"Track Live","type":"URL","example":"CN-4471902"},{"text":"Delivery Instructions","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Ravi","CN-4471902","2 PM and 6 PM","Suresh (+91 98xxxxxx21)"],"header":[]}$t$::jsonb, ARRAY[$t$delivery$t$,$t$tracking$t$]::text[], 20),

($t$logistics$t$, $t$lg-delivery-failed$t$, $t$Delivery Attempt Failed$t$, $t$Explain a failed attempt and offer a retry.$t$, $t$⚠️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Delivery Attempt Failed$t$,
 $t$Hi {{1}},

We tried to deliver *{{2}}* today at {{3}} but could not complete it — {{4}}.

Please choose a new delivery window and we will try again.$t$,
 $t$We will hold your parcel for 3 days$t$, $t$[{"text":"Reschedule Delivery","type":"QUICK_REPLY"},{"text":"Change Address","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Ravi","CN-4471902","3:15 PM","nobody was available at the address"],"header":[]}$t$::jsonb, ARRAY[$t$failed$t$,$t$retry$t$]::text[], 30),

($t$logistics$t$, $t$lg-delivered-pod$t$, $t$Delivered With Proof$t$, $t$Confirm delivery with who received it.$t$, $t$✅$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

Your parcel *{{2}}* was delivered on {{3}} at {{4}} and received by *{{5}}*.

Thank you for choosing us.$t$,
 $t$Reply if this looks incorrect$t$, $t$[{"url":"https://example.com/pod/{{1}}","text":"View Proof","type":"URL","example":"CN-4471902"}]$t$::jsonb, $t${"body":["Ravi","CN-4471902","17 August","4:05 PM","self"],"header":[]}$t$::jsonb, ARRAY[$t$pod$t$,$t$delivered$t$]::text[], 40)

) AS v(cat_slug, slug, title, description, emoji, meta_category, template_type, language,
       header_type, header_content, body_text, footer_text, buttons, sample_values, tags, position)
JOIN template_library_categories c ON c.slug = v.cat_slug
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title, description = EXCLUDED.description, emoji = EXCLUDED.emoji,
    meta_category = EXCLUDED.meta_category, template_type = EXCLUDED.template_type,
    language = EXCLUDED.language, header_type = EXCLUDED.header_type,
    header_content = EXCLUDED.header_content, body_text = EXCLUDED.body_text,
    footer_text = EXCLUDED.footer_text, buttons = EXCLUDED.buttons,
    sample_values = EXCLUDED.sample_values, tags = EXCLUDED.tags, position = EXCLUDED.position;
