-- Starter templates, part 2 of 2. Generated by scripts/generate-library-seed.mjs.
--
-- Written to PASS META REVIEW, which is stricter about wording than about
-- structure. Two rules drive every choice here:
--
--   * UTILITY must be transactional — about an order, account or booking the
--     customer already has. One promotional sentence in a utility template gets
--     it reclassified as marketing, which changes what it costs to send.
--   * Every variable ships with a REALISTIC sample value. Vague samples
--     ("test", "abc") are one of the most common rejection reasons, so the
--     library never leaves an operator to invent them.
--
-- Variables are contiguous from {{1}} — Meta rejects gaps — and footers carry no
-- variables, which Meta also forbids.
--
-- Idempotent on slug, so re-running refreshes the shipped copy without
-- duplicating rows and without touching templates an operator added themselves.

INSERT INTO template_library_templates (
  category_id, slug, title, description, emoji, meta_category, template_type, language,
  header_type, header_content, body_text, footer_text, buttons, sample_values, tags, position
)
SELECT c.id, v.slug, v.title, v.description, v.emoji, v.meta_category, v.template_type, v.language,
       v.header_type, v.header_content, v.body_text, v.footer_text, v.buttons, v.sample_values,
       v.tags, v.position
FROM (VALUES

($t$events$t$, $t$ev-invitation$t$, $t$Event Invitation$t$, $t$A warm invitation with date, venue and RSVP.$t$, $t$💌$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$You Are Invited$t$,
 $t$Dear {{1}}, 💌

You are warmly invited to *{{2}}*.

📅 {{3}}
📍 {{4}}
👗 Dress code: {{5}}

Your presence would mean a great deal to us.$t$,
 $t$Kindly RSVP by replying below$t$, $t$[{"text":"I Will Attend","type":"QUICK_REPLY"},{"text":"Cannot Make It","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mr. & Mrs. Rao","Aarav & Diya's Wedding","24 November, 7:00 PM onwards","The Grand Ballroom, Mumbai","Indian formal"],"header":[]}$t$::jsonb, ARRAY[$t$invitation$t$,$t$rsvp$t$]::text[], 10),

($t$events$t$, $t$ev-rsvp-confirmed$t$, $t$RSVP Confirmation$t$, $t$Thank a guest and confirm their seat.$t$, $t$✅$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Thank you {{1}}!

We have confirmed *{{2}}* guest(s) for {{3}} on {{4}}.

We will share the venue details and schedule closer to the date.$t$,
 $t$We look forward to seeing you$t$, $t$[{"text":"Update Guest Count","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mr. Rao","2","Aarav & Diya's Wedding","24 November"],"header":[]}$t$::jsonb, ARRAY[$t$rsvp$t$,$t$confirmation$t$]::text[], 20),

($t$events$t$, $t$ev-schedule$t$, $t$Event Day Schedule$t$, $t$Send the running order to guests.$t$, $t$📋$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Event Schedule$t$,
 $t$Hi {{1}},

Here is the schedule for {{2}} on *{{3}}*:

🕐 {{4}}
📍 Venue: {{5}}

Parking is available on site.$t$,
 $t$Reply if you need assistance$t$, $t$[{"url":"https://example.com/event/{{1}}","text":"View Full Schedule","type":"URL","example":"aarav-diya"}]$t$::jsonb, $t${"body":["Mr. Rao","the wedding celebrations","24 November","6:30 PM welcome drinks, 7:30 PM ceremony, 9:00 PM dinner","The Grand Ballroom, Mumbai"],"header":[]}$t$::jsonb, ARRAY[$t$schedule$t$,$t$event$t$]::text[], 30),

($t$events$t$, $t$ev-reminder$t$, $t$Event Reminder$t$, $t$A day-before reminder for confirmed guests.$t$, $t$⏰$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

A gentle reminder that {{2}} is tomorrow at *{{3}}*.

📍 {{4}}

We cannot wait to celebrate with you!$t$,
 $t$See you tomorrow$t$, $t$[{"url":"https://example.com/venue/{{1}}","text":"Get Directions","type":"URL","example":"grand-ballroom"}]$t$::jsonb, $t${"body":["Mr. Rao","Aarav & Diya's Wedding","7:00 PM","The Grand Ballroom, Mumbai"],"header":[]}$t$::jsonb, ARRAY[$t$reminder$t$,$t$event$t$]::text[], 40),

($t$retail$t$, $t$rt-store-offer$t$, $t$Store Offer$t$, $t$Drive footfall with a dated in-store offer.$t$, $t$🛒$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$This Weekend Only$t$,
 $t$Hi {{1}}! 🛒

This weekend at {{2}}: *{{3}}* on {{4}}.

Valid {{5}}. Show this message at the billing counter.$t$,
 $t$Offer valid at listed stores only$t$, $t$[{"text":"Find My Store","type":"QUICK_REPLY"},{"text":"Copy Code","type":"COPY_CODE","example":"WEEKEND20"}]$t$::jsonb, $t${"body":["Priya","Fresh Mart","20% off","fruits and vegetables","16–17 August"],"header":[]}$t$::jsonb, ARRAY[$t$offer$t$,$t$footfall$t$]::text[], 10),

($t$retail$t$, $t$rt-loyalty-points$t$, $t$Loyalty Points Update$t$, $t$Tell a member their points balance.$t$, $t$⭐$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

You earned *{{2}} points* on your purchase of {{3}} on {{4}}.

⭐ Total balance: {{5}} points

Redeem them on your next visit.$t$,
 $t$Points expire after 12 months$t$, $t$[{"text":"How To Redeem","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Priya","120","₹2,400","14 August","1,850"],"header":[]}$t$::jsonb, ARRAY[$t$loyalty$t$,$t$points$t$]::text[], 20),

($t$retail$t$, $t$rt-bill-receipt$t$, $t$Digital Bill$t$, $t$Send a digital receipt after billing.$t$, $t$🧾$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Your Receipt$t$,
 $t$Hi {{1}},

Thank you for shopping at {{2}}.

🧾 Bill number: {{3}}
💰 Amount paid: {{4}}
📅 {{5}}

Your digital receipt is available below.$t$,
 $t$Please retain for exchanges$t$, $t$[{"url":"https://example.com/bill/{{1}}","text":"View Receipt","type":"URL","example":"INV-88213"}]$t$::jsonb, $t${"body":["Priya","Fresh Mart, Baner","INV-88213","₹2,400","14 August"],"header":[]}$t$::jsonb, ARRAY[$t$receipt$t$,$t$billing$t$]::text[], 30),

($t$retail$t$, $t$rt-restock$t$, $t$Restock Alert$t$, $t$Tell shoppers a popular item is back.$t$, $t$🔔$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

*{{2}}* is back on our shelves at {{3}}.

It sells out quickly, so do drop in soon.$t$,
 $t$While stocks last$t$, $t$[{"text":"Reserve For Me","type":"QUICK_REPLY"},{"text":"Store Timings","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Priya","Organic Alphonso Mangoes","Fresh Mart, Baner"],"header":[]}$t$::jsonb, ARRAY[$t$restock$t$,$t$alert$t$]::text[], 40),

($t$restaurants$t$, $t$rs-order-confirmed$t$, $t$Food Order Confirmed$t$, $t$Confirm an order with ETA.$t$, $t$🍽️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Order Confirmed$t$,
 $t$Hi {{1}}! 🍽️

Your order from {{2}} is confirmed.

🆔 Order: {{3}}
💰 Total: {{4}}
⏱️ Ready in about {{5}}

We are cooking it fresh for you.$t$,
 $t$Reply if you need to change anything$t$, $t$[{"url":"https://example.com/order/{{1}}","text":"Track Order","type":"URL","example":"ORD-7781"},{"text":"Call Restaurant","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Kabir","Spice Route","ORD-7781","₹640","30 minutes"],"header":[]}$t$::jsonb, ARRAY[$t$order$t$,$t$food$t$]::text[], 10),

($t$restaurants$t$, $t$rs-table-booking$t$, $t$Table Reservation$t$, $t$Confirm a table with time and party size.$t$, $t$🪑$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Table Reserved$t$,
 $t$Hi {{1}},

Your table is reserved at {{2}}.

📅 {{3}}
👥 Guests: {{4}}
🆔 Reservation: {{5}}

We hold reservations for 15 minutes.$t$,
 $t$Reply to change your booking$t$, $t$[{"text":"Confirm","type":"QUICK_REPLY"},{"text":"Cancel Booking","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Kabir","Spice Route, Koregaon Park","17 August, 8:30 PM","4","RSV-2291"],"header":[]}$t$::jsonb, ARRAY[$t$reservation$t$,$t$table$t$]::text[], 20),

($t$restaurants$t$, $t$rs-out-for-delivery$t$, $t$Food Out For Delivery$t$, $t$Tell a customer food is on the way.$t$, $t$🛵$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

Your order *{{2}}* is on its way and should reach you in about *{{3}}*.

🛵 Rider: {{4}}$t$,
 $t$Enjoy your meal$t$, $t$[{"url":"https://example.com/track/{{1}}","text":"Track Rider","type":"URL","example":"ORD-7781"}]$t$::jsonb, $t${"body":["Kabir","ORD-7781","15 minutes","Imran (+91 98xxxxxx44)"],"header":[]}$t$::jsonb, ARRAY[$t$delivery$t$,$t$rider$t$]::text[], 30),

($t$restaurants$t$, $t$rs-daily-special$t$, $t$Today's Special$t$, $t$Promote the day's menu or offer.$t$, $t$🔥$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Today's Special$t$,
 $t$Hi {{1}}! 🔥

Today at {{2}}: *{{3}}* for just {{4}}.

Available {{5}} only. Order early — it goes fast!$t$,
 $t$Dine-in and delivery available$t$, $t$[{"url":"https://example.com/menu","text":"Order Now","type":"URL","example":""},{"text":"See Full Menu","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Kabir","Spice Route","Hyderabadi Dum Biryani","₹299","till 10 PM"],"header":[]}$t$::jsonb, ARRAY[$t$menu$t$,$t$promo$t$]::text[], 40),

($t$fitness$t$, $t$fn-membership-renewal$t$, $t$Membership Renewal$t$, $t$Remind a member before expiry.$t$, $t$💪$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Membership Expiring$t$,
 $t$Hi {{1}},

Your {{2}} membership at {{3}} expires on *{{4}}*.

Renew now to keep your streak going and lock in your current rate of {{5}}.$t$,
 $t$Speak to us about longer plans$t$, $t$[{"url":"https://example.com/renew/{{1}}","text":"Renew Now","type":"URL","example":"MEM-3391"},{"text":"Talk To Us","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Nikhil","quarterly","Iron House Gym","31 August","₹4,500"],"header":[]}$t$::jsonb, ARRAY[$t$membership$t$,$t$renewal$t$]::text[], 10),

($t$fitness$t$, $t$fn-class-booked$t$, $t$Class Booking Confirmed$t$, $t$Confirm a class or session slot.$t$, $t$🧘$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}},

You are booked for *{{2}}* on {{3}} at {{4}}.

👤 Trainer: {{5}}

Please arrive 5 minutes early and bring a towel.$t$,
 $t$Reply to cancel your slot$t$, $t$[{"text":"Confirm","type":"QUICK_REPLY"},{"text":"Cancel Booking","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Nikhil","Power Yoga","17 August","7:00 AM","Sneha"],"header":[]}$t$::jsonb, ARRAY[$t$class$t$,$t$booking$t$]::text[], 20),

($t$fitness$t$, $t$fn-free-trial$t$, $t$Free Trial Invite$t$, $t$Invite a prospect to a trial session.$t$, $t$🎁$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Free Trial Session$t$,
 $t$Hi {{1}}! 🎁

Come try {{2}} with a *free {{3}} session* — no commitment.

✅ {{4}}
📅 Available slots this week until {{5}}$t$,
 $t$Bring a friend along$t$, $t$[{"url":"https://example.com/trial","text":"Book Free Trial","type":"URL","example":""},{"text":"Call Us","type":"PHONE_NUMBER","phone_number":"+911234567890"}]$t$::jsonb, $t${"body":["Nikhil","Iron House Gym","one-day","Full gym access with a trainer-led intro","20 August"],"header":[]}$t$::jsonb, ARRAY[$t$trial$t$,$t$promo$t$]::text[], 30),

($t$fitness$t$, $t$fn-attendance-nudge$t$, $t$Come Back Nudge$t$, $t$Re-engage a member who has stopped visiting.$t$, $t$👋$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Hi {{1}}, we have missed you at {{2}}! 👋

It has been {{3}} since your last visit. Your {{4}} is still active until {{5}}.

Shall we book you a session to get back on track?$t$,
 $t$Your progress is waiting$t$, $t$[{"text":"Book A Session","type":"QUICK_REPLY"},{"text":"Talk To Trainer","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Nikhil","Iron House Gym","three weeks","quarterly membership","31 August"],"header":[]}$t$::jsonb, ARRAY[$t$retention$t$,$t$winback$t$]::text[], 40),

($t$saas$t$, $t$sa-welcome-onboarding$t$, $t$Welcome & Onboarding$t$, $t$Greet a new signup and point them to step one.$t$, $t$👋$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Welcome Aboard$t$,
 $t$Hi {{1}}, welcome to {{2}}! 👋

Your account is ready. The quickest way to see value is to *{{3}}* — it takes about {{4}}.

We are here if you need a hand.$t$,
 $t$Reply anytime for help$t$, $t$[{"url":"https://example.com/onboarding","text":"Get Started","type":"URL","example":""},{"text":"Book A Demo","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rohit","Replai","connect your WhatsApp number","2 minutes"],"header":[]}$t$::jsonb, ARRAY[$t$onboarding$t$,$t$welcome$t$]::text[], 10),

($t$saas$t$, $t$sa-trial-ending$t$, $t$Trial Ending Soon$t$, $t$Warn a trial user before it lapses.$t$, $t$⏳$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Trial Ending Soon$t$,
 $t$Hi {{1}},

Your {{2}} trial ends on *{{3}}* — that is {{4}} away.

Upgrade before then to keep your {{5}} and avoid any interruption.$t$,
 $t$Questions? Just reply here$t$, $t$[{"url":"https://example.com/upgrade","text":"Upgrade Now","type":"URL","example":""},{"text":"Talk To Sales","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rohit","Replai Pro","20 August","3 days","contacts, templates and automations"],"header":[]}$t$::jsonb, ARRAY[$t$trial$t$,$t$upgrade$t$]::text[], 20),

($t$saas$t$, $t$sa-payment-failed$t$, $t$Payment Failed$t$, $t$Ask a customer to fix a failed charge.$t$, $t$⚠️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Payment Could Not Be Processed$t$,
 $t$Hi {{1}},

We could not process your payment of *{{2}}* for {{3}} on {{4}}.

Please update your payment method to avoid your account being paused on {{5}}.$t$,
 $t$Your data is safe in the meantime$t$, $t$[{"url":"https://example.com/billing","text":"Update Payment","type":"URL","example":""},{"text":"Billing Help","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rohit","₹1,499","Replai Pro (monthly)","14 August","21 August"],"header":[]}$t$::jsonb, ARRAY[$t$billing$t$,$t$dunning$t$]::text[], 30),

($t$saas$t$, $t$sa-incident-update$t$, $t$Service Incident Update$t$, $t$Keep customers informed during an outage.$t$, $t$🔧$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Service Update$t$,
 $t$Hi {{1}},

We are investigating an issue affecting *{{2}}* since {{3}}.

Current status: {{4}}
Next update: {{5}}

We are sorry for the disruption.$t$,
 $t$Follow our status page for live updates$t$, $t$[{"url":"https://example.com/status","text":"Status Page","type":"URL","example":""}]$t$::jsonb, $t${"body":["Rohit","message delivery delays","10:20 AM","identified, fix being deployed","within 30 minutes"],"header":[]}$t$::jsonb, ARRAY[$t$incident$t$,$t$status$t$]::text[], 40),

($t$saas$t$, $t$sa-feature-launch$t$, $t$New Feature Launch$t$, $t$Announce something new to existing users.$t$, $t$🚀$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$New In Replai$t$,
 $t$Hi {{1}}! 🚀

*{{2}}* is now live.

{{3}}

It is available on your {{4}} plan at no extra cost. Have a look and tell us what you think.$t$,
 $t$We build from your feedback$t$, $t$[{"url":"https://example.com/whats-new","text":"See What's New","type":"URL","example":""},{"text":"Share Feedback","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Rohit","Carousel templates","Show up to 10 swipeable product cards in a single WhatsApp message.","Pro"],"header":[]}$t$::jsonb, ARRAY[$t$launch$t$,$t$announcement$t$]::text[], 50),

($t$legal$t$, $t$lg-consult-confirmed$t$, $t$Consultation Confirmed$t$, $t$Confirm a legal consultation slot.$t$, $t$⚖️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Consultation Confirmed$t$,
 $t$Dear {{1}},

Your consultation is confirmed.

👤 With: {{2}}
📅 {{3}}
📍 Mode: {{4}}
🆔 Reference: {{5}}

Please have any relevant documents ready.$t$,
 $t$Reply to reschedule$t$, $t$[{"text":"Confirm","type":"QUICK_REPLY"},{"text":"Reschedule","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mr. Deshmukh","Adv. R. Iyer","18 August, 3:00 PM","Video call","CON-2291"],"header":[]}$t$::jsonb, ARRAY[$t$consultation$t$,$t$booking$t$]::text[], 10),

($t$legal$t$, $t$lg-document-request$t$, $t$Document Request$t$, $t$Request paperwork needed for a matter.$t$, $t$📄$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Dear {{1}},

To proceed with {{2}}, we require the following: *{{3}}*.

Kindly share it by *{{4}}* so we can meet the filing timeline.$t$,
 $t$Shared documents are kept confidential$t$, $t$[{"text":"Send Documents","type":"QUICK_REPLY"},{"text":"Need Clarification","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mr. Deshmukh","your property registration matter","the original sale deed and PAN copy","20 August"],"header":[]}$t$::jsonb, ARRAY[$t$documents$t$,$t$request$t$]::text[], 20),

($t$legal$t$, $t$lg-case-update$t$, $t$Case Status Update$t$, $t$Update a client on progress.$t$, $t$📌$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Case Update$t$,
 $t$Dear {{1}},

An update on your matter *{{2}}*:

📌 Status: {{3}}
📅 Next hearing: {{4}}

We will keep you informed of any change.$t$,
 $t$Reply if you have questions$t$, $t$[{"text":"Request A Call","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mr. Deshmukh","Deshmukh vs. Municipal Corp.","Written submissions filed on 12 August","2 September"],"header":[]}$t$::jsonb, ARRAY[$t$case$t$,$t$update$t$]::text[], 30),

($t$legal$t$, $t$lg-invoice$t$, $t$Professional Fee Invoice$t$, $t$Send an invoice for services rendered.$t$, $t$🧾$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Invoice$t$,
 $t$Dear {{1}},

Please find our invoice for professional services.

🧾 Invoice: {{2}}
💰 Amount: {{3}}
📅 Due by: {{4}}
📋 For: {{5}}$t$,
 $t$Thank you for your business$t$, $t$[{"url":"https://example.com/invoice/{{1}}","text":"View Invoice","type":"URL","example":"INV-3392"}]$t$::jsonb, $t${"body":["Mr. Deshmukh","INV-3392","₹25,000","25 August","Consultation and drafting, August 2026"],"header":[]}$t$::jsonb, ARRAY[$t$invoice$t$,$t$billing$t$]::text[], 40),

($t$ngo$t$, $t$ng-donation-appeal$t$, $t$Donation Appeal$t$, $t$Ask supporters to contribute to a cause.$t$, $t$🙏$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Your Support Matters$t$,
 $t$Dear {{1}}, 🙏

We are raising funds for *{{2}}*.

🎯 Goal: {{3}}
📊 Raised so far: {{4}}

{{5}}

Every contribution helps. Thank you for standing with us.$t$,
 $t$Donations are eligible for 80G$t$, $t$[{"url":"https://example.com/donate","text":"Donate Now","type":"URL","example":""},{"text":"Know More","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mrs. Nair","school supplies for 500 children","₹5,00,000","₹3,20,000","₹1,000 provides a full year of books for one child."],"header":[]}$t$::jsonb, ARRAY[$t$donation$t$,$t$fundraising$t$]::text[], 10),

($t$ngo$t$, $t$ng-donation-receipt$t$, $t$Donation Receipt$t$, $t$Thank a donor and confirm the amount.$t$, $t$❤️$t$,
 $t$UTILITY$t$, $t$default$t$, $t$en_US$t$, NULL, NULL,
 $t$Dear {{1}},

Thank you for your generous donation of *{{2}}* towards {{3}} on {{4}}.

🆔 Receipt number: {{5}}

Your support makes our work possible.$t$,
 $t$Your 80G receipt is attached below$t$, $t$[{"url":"https://example.com/receipt/{{1}}","text":"Download Receipt","type":"URL","example":"DN-88120"}]$t$::jsonb, $t${"body":["Mrs. Nair","₹5,000","our education programme","14 August","DN-88120"],"header":[]}$t$::jsonb, ARRAY[$t$receipt$t$,$t$donation$t$]::text[], 20),

($t$ngo$t$, $t$ng-volunteer-drive$t$, $t$Volunteer Drive$t$, $t$Recruit volunteers for an activity.$t$, $t$🤝$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Volunteers Needed$t$,
 $t$Hi {{1}}! 🤝

We need volunteers for *{{2}}*.

📅 {{3}}
📍 {{4}}
⏱️ Commitment: {{5}}

Can you join us? Every pair of hands counts.$t$,
 $t$No experience necessary$t$, $t$[{"text":"Count Me In","type":"QUICK_REPLY"},{"text":"Tell Me More","type":"QUICK_REPLY"}]$t$::jsonb, $t${"body":["Mrs. Nair","our tree plantation drive","23 August, 7:00 AM","Riverside Park, Pune","about 3 hours"],"header":[]}$t$::jsonb, ARRAY[$t$volunteer$t$,$t$drive$t$]::text[], 30),

($t$ngo$t$, $t$ng-event-mobilise$t$, $t$Event Mobilisation$t$, $t$Invite supporters to a public event.$t$, $t$📣$t$,
 $t$MARKETING$t$, $t$default$t$, $t$en_US$t$, $t$text$t$, $t$Join Us$t$,
 $t$Dear {{1}}, 📣

Join us for *{{2}}* on *{{3}}* at {{4}}.

{{5}}

Your presence will make a real difference.$t$,
 $t$Share this with friends and family$t$, $t$[{"text":"I Will Join","type":"QUICK_REPLY"},{"url":"https://example.com/event","text":"Event Details","type":"URL","example":""}]$t$::jsonb, $t${"body":["Mrs. Nair","the Clean City Rally","24 August, 8:00 AM","Shivaji Nagar Ground","We expect over 2,000 citizens to walk with us."],"header":[]}$t$::jsonb, ARRAY[$t$event$t$,$t$mobilisation$t$]::text[], 40)

) AS v(cat_slug, slug, title, description, emoji, meta_category, template_type, language,
       header_type, header_content, body_text, footer_text, buttons, sample_values, tags, position)
JOIN template_library_categories c ON c.slug = v.cat_slug
ON CONFLICT (slug) DO UPDATE
SET title = EXCLUDED.title, description = EXCLUDED.description, emoji = EXCLUDED.emoji,
    meta_category = EXCLUDED.meta_category, template_type = EXCLUDED.template_type,
    language = EXCLUDED.language, header_type = EXCLUDED.header_type,
    header_content = EXCLUDED.header_content, body_text = EXCLUDED.body_text,
    footer_text = EXCLUDED.footer_text, buttons = EXCLUDED.buttons,
    sample_values = EXCLUDED.sample_values, tags = EXCLUDED.tags, position = EXCLUDED.position;
