-- ============================================================
-- Store the two-step verification PIN set during registration.
--
-- WHY THIS COLUMN HAS TO EXIST
--
-- Activating a number on the Cloud API requires
-- POST /{phone_number_id}/register, and that call takes a 6-digit
-- `pin`. When the number has no two-step verification yet
-- (is_pin_enabled = false), the PIN supplied in that call BECOMES the
-- number's permanent two-step PIN on Meta's side.
--
-- Embedded Signup never asks the operator for a PIN, so the app has to
-- generate one. If it generates a PIN, registers with it, and then
-- forgets it, the operator is permanently locked out of their own
-- two-step verification settings in WhatsApp Manager — and Meta offers
-- no way to read a PIN back. Generating a credential on someone's
-- behalf and discarding it is worse than not generating one at all.
--
-- Encrypted at rest with the same AES-256-GCM helper as access_token
-- (src/lib/whatsapp/encryption.ts). It is a shared secret with Meta,
-- not a hash target: it must be recoverable in plaintext to be shown
-- to the operator or replayed to /register, so hashing is not an
-- option here.
--
-- Nullable on purpose. Rows predating this migration have no stored
-- PIN, and numbers connected through Manual setup use a PIN the
-- operator already knows and chose themselves — in that case we have no
-- business storing it.
-- ============================================================

ALTER TABLE whatsapp_config
  ADD COLUMN IF NOT EXISTS two_step_pin TEXT;

COMMENT ON COLUMN whatsapp_config.two_step_pin IS
  'AES-256-GCM encrypted 6-digit two-step verification PIN generated by this app during POST /{phone_number_id}/register. NULL when the operator supplied their own PIN (manual setup) or the row predates automatic registration. Meta cannot return a PIN, so this is the only copy.';
